/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSArray, NSString, NSDictionary;

@interface CBAPIRequest : XXUnknownSuperclass {
@private
	NSString* controller;
	NSString* action;
	NSMutableDictionary* body;
	NSMutableDictionary* query;
	NSArray* params;
	id contextInfo;
	id contextBlock;
}
@property(copy, nonatomic) id contextBlock;
@property(retain, nonatomic) NSArray* params;
@property(retain, nonatomic) NSDictionary* query;
@property(retain, nonatomic) NSDictionary* body;
@property(retain, nonatomic) NSString* action;
@property(retain, nonatomic) NSString* controller;
+(id)requestWithController:(id)controller action:(id)action;
-(void)dealloc;
-(void)signWithAppId:(id)appId appSignature:(id)signature;
-(id)serializeDictionaryToStringForSignature:(id)signature;
-(void)appendDeviceInfoParams;
-(void)appendQueryArgumentKey:(id)key value:(id)value;
-(void)appendBodyArgumentKey:(id)key value:(id)value;
-(id)initWithController:(id)controller action:(id)action;
@end

