/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"


@interface CBContextualizedBasicAnimation : XXUnknownSuperclass {
@private
	id context;
}
@property(retain) id context;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

