/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CBUnderfinedProgressBar, UILabel;

@interface CBLoadingView : XXUnknownSuperclass {
@private
	UILabel* label;
	CBUnderfinedProgressBar* progressBar;
}
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

