/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer;

@interface CBUnderfinedProgressBar : XXUnknownSuperclass {
@private
	NSTimer* timer;
	float offset;
}
-(void)drawRect:(CGRect)rect;
-(void)step:(id)step;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

