/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL;
@protocol CBUrlOpenerDelegate;

@interface CBURLOpener : XXUnknownSuperclass {
@private
	id<CBUrlOpenerDelegate> delegate;
	NSURL* lastUrl;
}
@property(retain) NSURL* lastUrl;
@property(assign) id<CBUrlOpenerDelegate> delegate;
+(id)openerWithDelegate:(id)delegate;
-(void)dealloc;
-(void)connectionDidFinishLoading:(id)connection;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
-(void)open:(id)open;
@end

