/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary;

@interface CBView : XXUnknownSuperclass {
@private
	NSDictionary* responseContext;
	NSString* location;
	int state;
	int type;
}
@property(retain) NSString* location;
@property(assign) int type;
@property(assign) int state;
@property(retain) NSDictionary* responseContext;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

