/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class Image;

__attribute__((visibility("hidden")))
@interface CharDef : XXUnknownSuperclass {
@private
	int charID;
	int x;
	int y;
	int width;
	int height;
	int xOffset;
	int yOffset;
	int xAdvance;
	Image* image;
	float scale;
}
@property(assign, nonatomic) float scale;
@property(assign, nonatomic) int xAdvance;
@property(assign, nonatomic) int yOffset;
@property(assign, nonatomic) int xOffset;
@property(assign, nonatomic) int height;
@property(assign, nonatomic) int width;
@property(assign, nonatomic) int y;
@property(assign, nonatomic) int x;
@property(assign, nonatomic) int charID;
@property(retain, nonatomic) Image* image;
-(void)dealloc;
-(id)description;
-(id)initCharDefWithFontImage:(id)fontImage scale:(float)scale;
@end

