/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "UIWebViewDelegate.h"
#import "CBAPIConnectionDelegate.h"
#import "CBUrlOpenerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, CBAPIConnection, CBView, NSString;
@protocol ChartBoostDelegate;

@interface ChartBoost : XXUnknownSuperclass <CBAPIConnectionDelegate, UIWebViewDelegate, CBUrlOpenerDelegate> {
@private
	NSString* appId;
	NSString* appSignature;
	id<ChartBoostDelegate> delegate;
	CBAPIConnection* connection;
	NSMutableDictionary* cachedInterstitials;
	CBView* cachedMoreApps;
}
@property(assign) id<ChartBoostDelegate> delegate;
@property(retain) NSString* appSignature;
@property(retain) NSString* appId;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedChartBoost;
-(void)didReceiveAPIResponse:(id)response forRequest:(id)request;
-(void)didFailToReceiveAPIResponseForRequest:(id)request;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)webViewDidFinishLoad:(id)webView;
-(void)urlWillOpen:(id)url;
-(void)attemptShowingMoreApps:(id)apps;
-(void)attemptShowingInterstitial:(id)interstitial;
-(void)clickResponseReceived:(id)received forwardToURL:(id)url;
-(void)handleChartBoostRequest:(id)request forMoreApps:(id)moreApps;
-(void)handleChartBoostRequest:(id)request forInterstitial:(id)interstitial;
-(void)loadChartBoostViewForResponse:(id)response type:(int)type shouldCache:(BOOL)cache location:(id)location;
-(void)loadMoreAppsShouldCache:(BOOL)loadMoreApps;
-(void)loadInterstitial:(id)interstitial shouldCache:(BOOL)cache;
-(void)handleChartBoostViewError:(int)error;
-(void)showMoreApps;
-(void)cacheMoreApps;
-(void)showInterstitial:(id)interstitial;
-(void)showInterstitial;
-(void)cacheInterstitial:(id)interstitial;
-(void)cacheInterstitial;
-(void)install;
-(void)dealloc;
-(id)init;
-(id)autorelease;
-(oneway void)release;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

