/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class EasyGlyph, MultiplayerTextField, NSString, NSMutableArray, Texture2D;

__attribute__((visibility("hidden")))
@interface Chat : XXUnknownSuperclass {
@private
	MultiplayerTextField* textField;
	NSString* text[3];
	Color textColor[3];
	Texture2D* text_texture[3];
	EasyGlyph* font;
	float ratio;
	BOOL iPod4;
	BOOL iPad;
	int textField_currentRotation;
	float dTime;
	NSMutableArray* screen_effectArray_fadeIn;
	NSMutableArray* screen_effectArray_fadeOut;
	NSMutableArray* chatWindow_fadeOut;
	BOOL textField_fadeIn;
	BOOL drawingChatWindow_shortRun;
	BOOL drawingChatWindow_main;
	NSString* baseText;
	BOOL screenRotation;
}
-(BOOL)isScreenRotated;
-(void)setScreenRotation:(float)rotation;
-(BOOL)isMainChatActive;
-(void)dealloc;
-(BOOL)isTyping;
-(void)releaseTextField;
-(void)touchEnded:(CGPoint)ended;
-(void)touchMoved:(CGPoint)moved;
-(void)touchBegan:(CGPoint)began;
-(void)activateOrDeactivateTextFieldWithKeyboard;
-(void)createMultiplayerTextFieldWithText:(id)text;
-(void)createMultiplayerTextField;
-(void)clearChatWindow;
-(void)addMessage:(id)message color:(Color)color;
-(void)addMessage:(id)message yourMessage:(BOOL)message2;
-(void)addSystemMessage:(id)message;
-(void)checkingDeviceOrientation;
-(void)update;
-(void)draw;
-(void)showChatWindow_main;
-(void)showChatWindow_shortRun;
-(void)drawFade;
-(void)startFadeOut;
-(void)startFadeIn;
-(void)setdTime:(float)time;
-(id)initWithFont:(id)font ratio:(float)ratio dTime:(float)time iPod4:(BOOL)a4 iPad:(BOOL)pad;
@end

