/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface CLSCrashReportBinaryImageInfo : XXUnknownSuperclass {
@private
	unsigned long long _baseAddress;
	unsigned long long _imageSize;
	NSString* _imageName;
	BOOL _hasImageUUID;
	NSString* _imageUUID;
}
@property(readonly, assign, nonatomic) NSString* imageUUID;
@property(readonly, assign, nonatomic) BOOL hasImageUUID;
@property(readonly, assign, nonatomic) NSString* imageName;
@property(readonly, assign, nonatomic) unsigned long long imageSize;
@property(readonly, assign, nonatomic) unsigned long long imageBaseAddress;
-(void)dealloc;
-(id)initWithImageBaseAddress:(unsigned long long)imageBaseAddress imageSize:(unsigned long long)size imageName:(id)name imageUUID:(id)uuid;
@end

