/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface CLSCrashTest : XXUnknownSuperclass {
	int threadToCrashOn;
	int crashType;
}
@property(assign) int crashType;
@property(assign) int threadToCrashOn;
-(BOOL)crashByRecursingInfinitely;
-(void)crashByAccessingBadMemory;
-(void)crashByAccessingNULLPointer;
-(void)crashByThrowingCocoaException;
-(void)crashWithCrashTestOfType:(int)type;
-(void)crash:(id)crash;
-(id)init;
@end

