/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "CLSCrashReport.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface CLSCrashReport : XXUnknownSuperclass {
@private
	CLSCrashReportDecoder* _decoder;
	NSArray* _images;
}
@property(readonly, assign, nonatomic) CLSCrashReportDecoder* decoder;
@property(readonly, assign, nonatomic) NSArray* images;
-(void)dealloc;
-(id)initWithData:(id)data error:(id*)error;
@end

@interface CLSCrashReport (PrivateMethods)
-(void)updateFrame:(Crashlytics__Session__Event__Application__Execution__Thread__Frame*)frame withAddressInfo:(unsigned long long)addressInfo;
-(void)symbolicateFrame:(Crashlytics__Session__Event__Application__Execution__Thread__Frame*)frame binaryImages:(id)images;
-(id)imageForAddress:(unsigned long long)address;
-(id)dictionaryWithBinaryImagesKeyedByUUID;
-(id)extractImageInfo:(Crashlytics__Session__Event__Application__Execution*)info error:(id*)error;
-(Crashlytics__Session*)decodeCrashData:(id)data error:(id*)error;
@end

