/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "CLSCrashSignalHandler.h"


@interface CLSCrashSignalHandler : XXUnknownSuperclass {
@private
	darwin_sigaltstack _sigstk;
}
+(void)setEnableReraise:(BOOL)reraise;
+(id)sharedHandler;
+(void)initialize;
-(BOOL)registerSignalHandlerDidCompleteDelegate:(id)registerSignalHandler selector:(SEL)selector;
-(BOOL)registerHandlerWithCallback:(/*function-pointer*/ void*)callback context:(void*)context error:(id*)error;
-(BOOL)registerHandlerForSignal:(int)signal index:(int)index error:(id*)error;
-(id)init;
@end

@interface CLSCrashSignalHandler (PrivateMethods)
-(void)populateError:(id*)error errorCode:(int)code description:(id)description cause:(id)cause;
-(void)populateError:(id*)error errnoVal:(int)val description:(id)description;
@end

