/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSData, NSString, NSDate;

@interface CLSSessionReport : XXUnknownSuperclass {
	NSString* _path;
	NSData* _data;
	NSDate* _date;
	NSMutableDictionary* _attributes;
	NSString* _attributesFilePath;
}
@property(retain, nonatomic) NSDate* date;
@property(retain, nonatomic) NSString* path;
+(id)reportWithCrashFilePath:(id)crashFilePath;
-(void)appendMultipartMIMEData:(id)data forKey:(id)key value:(id)value boundary:(id)boundary;
-(id)dataForMultipartMIMEWithDictionary:(id)dictionary boundary:(id)boundary;
-(BOOL)sendToURL:(id)url;
-(BOOL)remove;
-(void)dealloc;
-(id)init;
-(id)initWithCrashData:(id)crashData;
-(id)initWithCrashFilePath:(id)crashFilePath;
@end

