/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString;

@interface CLSSettings : XXUnknownSuperclass {
	NSDictionary* _settings;
	NSString* _status;
	NSString* _apiKey;
	NSString* _applicationIdentifier;
	NSString* _version;
	NSString* _shortVersion;
	NSString* _cacheDirectory;
}
-(id)cachedSettingsInDirectory:(id)directory ignoringExpiredCache:(BOOL)cache;
-(BOOL)cacheSettings:(id)settings inDirectory:(id)directory;
-(id)parsedData:(id)data ignoringExpiredCache:(BOOL)cache;
-(id)settingsFromServer;
-(id)load;
-(BOOL)collectOnSimulator;
-(id)crashSubmissionURL;
-(id)interactivePromptCancelButtonTitle;
-(id)interactivePromptAlwaysSendButtonTitle;
-(id)interactivePromptSendButtonTitle;
-(BOOL)interactivePromptShouldIncludeAlwaysSendButton;
-(BOOL)interactivePromptShouldIncludeCancelButton;
-(id)interactivePromptMessage;
-(id)interactivePromptTitle;
-(void)setUserDesiresReportsAlwaysBeSent:(BOOL)sent;
-(BOOL)userDesiresReportsAlwaysBeSent;
-(BOOL)requestUserPermissionBeforeSendingCrashReports;
-(BOOL)shouldReportUDID;
-(BOOL)shouldReportCrashes;
-(void)dealloc;
-(id)initWithAPIKey:(id)apikey applicationIdentifier:(id)identifier version:(id)version shortVersion:(id)version4 cacheDirectory:(id)directory;
@end

