/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface CLSUtils : XXUnknownSuperclass {
}
+(id)SUDID;
+(id)deviceID;
+(BOOL)isSimulator;
+(id)urlEncode:(id)encode;
+(id)SHA1StringFromString:(id)string salt:(id)salt;
@end

