/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"


__attribute__((visibility("hidden")))
@interface CommonFunctions : XXUnknownSuperclass {
}
+(void)drawRectangle:(CGRect)rectangle red:(float)red green:(float)green blue:(float)blue;
+(void)drawRectangle:(CGRect)rectangle red:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;
+(void)drawRectangle:(CGRect)rectangle;
+(void)drawText:(id)text atPosition:(CGPoint)position withAlignment:(int)alignment r:(float)r g:(float)g b:(float)b alpha:(float)alpha scale:(CGPoint)scale rotation:(float)rotation;
+(BOOL)isInRect:(CGRect)rect point:(CGPoint)point;
@end

