/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSObject, NSString;
@protocol CrashlyticsDelegate;

@interface Crashlytics : XXUnknownSuperclass {
@private
	NSString* _apiKey;
	NSString* _dataDirectory;
	NSString* _bundleIdentifier;
	BOOL _installed;
	NSMutableDictionary* _customAttributes;
	id _user;
	int _sendButtonIndex;
	int _alwaysSendButtonIndex;
	NSObject<CrashlyticsDelegate>* _delegate;
}
@property(assign, nonatomic) NSObject<CrashlyticsDelegate>* delegate;
@property(assign, nonatomic) BOOL debugMode;
@property(readonly, assign, nonatomic) NSString* version;
@property(copy, nonatomic) NSString* apiKey;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedInstance;
+(id)hostInfoPlistValueForKey:(id)key;
+(id)APIEndpoint;
+(id)startWithAPIKey:(id)apikey delegate:(id)delegate afterDelay:(double)delay;
+(id)startWithAPIKey:(id)apikey delegate:(id)delegate;
+(id)startWithAPIKey:(id)apikey afterDelay:(double)delay;
+(id)startWithAPIKey:(id)apikey;
-(id)autorelease;
-(oneway void)release;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
-(void)startCrashDetector;
-(void)reportException:(id)exception;
-(id)dataDirectory;
-(id)shortBundleVersion;
-(id)bundleVersion;
-(id)bundleIdentifier;
-(id)applicationName;
-(id)customAttributeForKey:(id)key;
-(void)addCustomAttribute:(id)attribute forKey:(id)key;
-(void)addCustomAttributesFromDictionary:(id)dictionary;
-(void)setUserIdentifier:(id)identifier;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)ignoreReports;
-(void)sendReportsWithApplicationApproval;
-(void)sendReportsWithUserApproval;
-(void)detectNewCrashReports;
-(void)removeMarkerFile;
-(void)processCrashes;
-(void)crash;
-(void)retryProcessingCrashesAfterDelay:(id)delay;
-(void)processCrashesInBackground;
-(void)processCrashesOnMainThreadAfterDelay:(id)delay;
-(id)processCrashesAfterDelay:(double)delay;
-(id)initializeWithAPIKey:(id)apikey;
-(void)dealloc;
-(id)init;
@end

