/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class EasyGlyph, NSCalendar, NSString, NSMutableArray, Texture2D;

__attribute__((visibility("hidden")))
@interface DailySurprise : XXUnknownSuperclass {
@private
	int firstDayInSecondsFromOurServer;
	int daysInStraight;
	int firstDayInSeconds;
	int nextDateInSeconds;
	BOOL gotSurprise;
	BOOL checked;
	NSCalendar* gregorian;
	Texture2D* textures[11];
	int bonusType;
	BOOL drawing;
	BOOL textureLoaded;
	NSString* deviceType;
	NSMutableArray* effect_fadeIn;
	NSMutableArray* effect_fadeOut;
	NSMutableArray* effectScale;
	float dTime;
	BOOL drawingFadeIn;
	EasyGlyph* easyGlyph;
	float bonusMultiplier;
}
-(BOOL)isDrawing;
-(void)hide;
-(void)load;
-(void)save;
-(void)saveFirstDay;
-(void)setNextDate;
-(id)currentLocalDate;
-(id)getNextDate;
-(BOOL)isFileExist;
-(int)timeIntervalSince1970FromOurServer;
-(BOOL)isOnline;
-(BOOL)canGetSurprise;
-(int)getMaxDaysInStraightFromOurServer;
-(void)checkDailySurprise;
-(void)getSurprise;
-(void)drawAtPoint:(CGPoint)point ratio:(float)ratio;
-(void)show;
-(void)unloadTextures;
-(void)loadTexture;
-(void)setEasyGlyph:(id)glyph;
-(void)dealloc;
-(id)initWithDeviceType:(id)deviceType dTime:(float)time;
@end

