/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, EasyGlyph, NSString;

__attribute__((visibility("hidden")))
@interface Drawable : XXUnknownSuperclass {
@private
	BOOL _iPad;
	BOOL _iPod4;
	BOOL _iPadNew;
	NSString* deviceType;
	float dTime;
	float ratio;
	float retinaScale;
	CGPoint deviceTranslate;
	CGPoint screenShift;
	float deviceScale;
	EasyGlyph* easyGlyph;
	EasyGlyph* easyGlyphSmaller;
	NSMutableDictionary* dTexts;
}
-(void)drawPreMatchNames;
-(void)drawRectangle:(CGRect)rectangle red:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;
-(BOOL)isInRect:(CGRect)rect point:(CGPoint)point raw:(BOOL)raw;
-(void)drawRect:(CGRect)rect withAngle:(float)angle fillColor:(Color4f)color;
-(void)drawRect:(CGRect)rect fillColor:(Color4f)color;
-(void)placeTexture:(id)texture translate:(CGPoint)translate rotate:(float)rotate scale:(CGPoint)scale alignment:(int)alignment color:(Color4f)color;
-(void)placeTexture:(id)texture translate:(CGPoint)translate rotate:(float)rotate scale:(CGPoint)scale;
-(void)placeTexture:(id)texture translate:(CGPoint)translate;
-(void)placeTexture:(id)texture translate:(CGPoint)translate rotate:(float)rotate;
-(void)placeTexture:(id)texture translate:(CGPoint)translate scale:(CGPoint)scale;
-(void)dealloc;
-(id)platform;
-(void)detectDevice;
-(id)init;
@end

