/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAccelerometerDelegate.h"
#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIScrollViewDelegate.h"

@class NSTimer, CMMotionManager, UIScrollView;
@protocol ESRenderer;

__attribute__((visibility("hidden")))
@interface EAGLView : XXUnknownSuperclass <UIScrollViewDelegate, UIAccelerometerDelegate> {
@private
	id<ESRenderer> renderer;
	BOOL animating;
	BOOL displayLinkSupported;
	int animationFrameInterval;
	id displayLink;
	NSTimer* animationTimer;
	BOOL _iPad;
	UIScrollView* awardScroll;
	CMMotionManager* motionManager;
}
@property(assign, nonatomic) int animationFrameInterval;
@property(readonly, assign, nonatomic, getter=isAnimating) BOOL animating;
+(Class)layerClass;
-(id)getRenderer;
-(void)dealloc;
-(BOOL)isInRect:(CGRect)rect point:(CGPoint)point;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)accelerometer:(id)accelerometer didAccelerate:(id)accelerate;
-(void)stopAnimation;
-(void)startAnimation;
-(int)viewType;
-(void)layoutSubviews;
-(void)updateMedals:(int)medals;
-(BOOL)canShowAd;
-(void)drawView:(id)view;
-(void)setWeaponsCampPause:(BOOL)pause;
-(void)saveShopMenu;
-(id)platform;
-(void)detectDevice;
-(id)initWithCoder:(id)coder;
@end

