/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface EasyGlyph : XXUnknownSuperclass {
@private
	UIImage* fontUIImage;
	NSMutableDictionary* characterDict;
	float kerning;
	int charSetLength;
	NSString* charSet;
}
+(CGRect)getRectFromTargetHeight:(float)targetHeight :(float)arg2 :(float)arg3 :(CGPoint)arg4 :(int)arg5 :(int)arg6;
+(CGRect)getRectFromTargetWidth:(float)targetWidth :(float)arg2 :(float)arg3 :(CGPoint)arg4 :(int)arg5 :(int)arg6;
+(id)imageByCropping:(id)cropping toRect:(CGRect)rect;
-(void)dealloc;
-(id)cleanString:(id)string;
-(id)writeTextToTexture:(id)texture textureSize:(CGSize)size alignment:(int)alignment spacing:(float)spacing;
-(id)writeTextToTexture:(id)texture textureSize:(CGSize)size alignment:(int)alignment;
-(id)writeTextToTexture:(id)texture maxWidth:(float)width;
-(id)writeTextToTexture:(id)texture forceWidth:(float)width;
-(id)writeTextToTexture:(id)texture;
-(int)heightForText:(id)text ofWidth:(float)width;
-(float)wordWidth:(id)width;
-(void)initFont:(id)font :(id)arg2 :(id)arg3;
@end

