/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface EasyGlyphChar : XXUnknownSuperclass {
@private
	BOOL character;
	float x;
	float y;
	float w;
	float h;
	float kernx1;
	float kernx2;
}
@property(assign) float kernx2;
@property(assign) float kernx1;
@property(assign) float h;
@property(assign) float w;
@property(assign) float y;
@property(assign) float x;
@property(assign) BOOL character;
@end

