/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Drawable.h"
#import "Overkill-Structs.h"

@class ExperienceBar, Texture2D;

__attribute__((visibility("hidden")))
@interface Endround : Drawable {
@private
	Texture2D* _texture[3];
	int levelScore;
	int bonusMoney;
	int totalScore;
	int levelMoney;
	int totalMoney;
	ExperienceBar* bar;
	BOOL deallocEasyGlyph;
	BOOL buttonClicked;
	float drawingTime;
	int didyouknowIndex;
}
-(void)drawAtPosition:(CGPoint)position;
-(void)buttonClicked;
-(void)dealloc;
-(void)setDeviceType:(id)type;
-(void)loadTextures;
-(id)initWithLevelScore:(int)levelScore bonusMoney:(int)money totalScore:(int)score levelMoney:(int)money4 totalMoney:(int)money5;
@end

