/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "ESRenderer.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class WeaponsCampView, EasyGlyph, Multiplayer_WeaponsShopView, NSMutableData, MenuView, Drawable, Endround, SingletonTextureManager, EAGLContext, NSString, WeaponsShopView, SingletonSoundManager, UIScrollView, Texture2D;

__attribute__((visibility("hidden")))
@interface ES1Renderer : XXUnknownSuperclass <ESRenderer> {
@private
	EAGLContext* context;
	EAGLContext* contextB;
	int backingWidth;
	int backingHeight;
	unsigned defaultFramebuffer;
	unsigned colorRenderbuffer;
	CGPoint screenShift;
	CGPoint deviceTranslate;
	float ratio;
	float deviceScale;
	NSString* deviceType;
	float dTime;
	int _viewType;
	WeaponsShopView* view_shopMenu;
	Multiplayer_WeaponsShopView* view_shopMenuMultiplayer;
	WeaponsCampView* view_weaponsCamp;
	MenuView* view_mainMenu;
	Endround* endround;
	int _loadState;
	int _unloadState;
	Texture2D* _texture[7];
	BOOL _iPad;
	BOOL _iPod4;
	BOOL isReleased;
	BOOL firstScreen;
	BOOL _iPadNew;
	BOOL view_shopMenu_release;
	BOOL view_weaponsCamp_release;
	BOOL view_mainMenu_release;
	BOOL view_shopMenuMultiplayer_release;
	UIScrollView* awardScroll;
	float backgroundJobTime;
	BOOL _backgroundThread;
	float timeSinceLastBullet;
	int knownPercentage;
	int timedPieces;
	SingletonTextureManager* sharedTextureManager;
	SingletonSoundManager* sharedSoundManager;
	BOOL _GCavailable;
	BOOL _userLoggedIn;
	NSMutableData* receivedData;
	int _earnedMedals;
	EasyGlyph* easyGlyph;
	float timeInFirstScreen;
	int tipCounter;
	Music music;
	BOOL showWhiteScreen;
	int whiteScreenCounter;
	int threadDelay;
	BOOL _screenRotated;
	BOOL catchPercentData;
	Drawable* drawable;
	BOOL preMatchTexturesLoaded;
	Texture2D* preMatchTextures[7];
}
-(id).cxx_construct;
-(void)dealloc;
-(BOOL)isScreenRotated;
-(int)viewType;
-(BOOL)canShowAd;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)updateMedals:(int)medals;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event withView:(id)view;
-(void)touchesEnded:(id)ended withEvent:(id)event withView:(id)view;
-(void)touchesMoved:(id)moved withEvent:(id)event withView:(id)view;
-(void)touchesBegan:(id)began withEvent:(id)event withView:(id)view;
-(void)accelerometer:(id)accelerometer didAccelerate:(id)accelerate;
-(BOOL)resizeFromLayer:(id)layer;
-(void)backgroundJob;
-(void)startTheBackgroundJob;
-(void)musicController;
-(void)nextMusic;
-(void)resetMusicControler;
-(void)releasePreMatchTextures;
-(void)render;
-(void)refreshPreMatchTextures;
-(void)saveShopMenu;
-(void)unloadTextures;
-(void)loadTextures;
-(void)doStuff;
-(void)setWeaponsCampPause:(BOOL)pause;
-(void)detectDevice;
-(id)platform;
-(id)init;
@end

