/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ESRenderer <NSObject>
-(int)viewType;
-(void)setUnloadState:(int)state;
-(void)accelerometer:(id)accelerometer didAccelerate:(id)accelerate;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)saveShopMenu;
-(void)setWeaponsCampPause:(BOOL)pause;
-(BOOL)resizeFromLayer:(id)layer;
-(void)render;
@end

