/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "Drawable.h"
#import "NSXMLParserDelegate.h"

@class Texture2D;

__attribute__((visibility("hidden")))
@interface ExperienceBar : Drawable <NSXMLParserDelegate> {
@private
	int points;
	Texture2D* _texture[4];
	int lowerExp;
	int higherExp;
	Rank lowerRank;
	Rank higherRank;
}
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
-(void)parseXml:(id)xml;
-(void)drawBar:(CGPoint)bar scale:(BOOL)scale;
-(void)drawBar:(CGPoint)bar;
-(void)doStuff;
-(void)dealloc;
-(id)initWithPoints:(int)points;
@end

