/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate;

__attribute__((visibility("hidden")))
@interface FAADTracking : XXUnknownSuperclass {
@private
	NSDate* startTime_;
	double sessionTime_;
}
@property(retain, nonatomic) NSDate* startTime;
-(void)trackWake;
-(void)trackLaunchWhenAppBecomesActive;
-(void)trackLaunchWhenAppComeToForeground;
-(void)trackLaunchWhenAppGoesInBackground;
-(void)trackLaunchWhenAppShutsDown;
-(void)registerForDeviceNotifications;
@end

