/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class FAADNetworkWebService, FAADAdsController, FAADOfferClickedWebService, NSString;

__attribute__((visibility("hidden")))
@interface FAADNetwork : XXUnknownSuperclass {
@private
	NSString* integrationKey_;
	NSString* secretKey_;
	FAADAdsController* faadAds_;
	FAADNetworkWebService* faadNetworkService_;
	FAADOfferClickedWebService* faadOfferClicked_;
	int currentDevice_;
}
@property(assign) int currentDevice;
@property(retain, nonatomic) FAADOfferClickedWebService* faadOfferClicked;
@property(retain, nonatomic) FAADNetworkWebService* faadNetworkService;
@property(retain, nonatomic) FAADAdsController* faadAds;
@property(retain, nonatomic) NSString* secretKey;
@property(retain, nonatomic) NSString* integrationKey;
+(id)alloc;
+(id)sharedFAADNetwork;
-(void)dealloc;
-(void)downloadFeedWithId:(int)anId;
-(void)getNetworkFeeds:(id)feeds;
-(void)displayLandscapeAdsWithStatusBar:(BOOL)statusBar;
-(void)displayPortraitAdsWithStatusBar:(BOOL)statusBar;
-(void)unRegisterForFAADNotifications;
-(void)registerForFAADNotifications;
-(void)FAADNetworkFailedToConnect:(id)connect;
-(void)FAADNetworkConnected:(id)connected;
-(void)connectWithIntegrationKey:(id)integrationKey andSecretKey:(id)key;
-(id)init;
-(id)getConnectionParameters;
-(void)checkforDevice;
@end

