/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSMutableURLRequest, NSData, NSString, NSMutableData, NSURLConnection;
@protocol FAADHttpRequestDelegate;

__attribute__((visibility("hidden")))
@interface FAADHttpRequest : XXUnknownSuperclass {
@private
	NSString* url_;
	NSMutableData* responseData_;
	NSURLConnection* urlConnection_;
	NSURL* requestUrl_;
	NSMutableURLRequest* request_;
	NSString* requestType_;
	int connectCount_;
	int isJson_;
	id<FAADHttpRequestDelegate> delegate_;
}
@property(assign) int isJson;
@property(assign) int connectCount;
@property(assign) id<FAADHttpRequestDelegate> delegate;
@property(copy, nonatomic) NSString* requestType;
@property(retain, nonatomic) NSMutableURLRequest* request;
@property(retain, nonatomic) NSURL* requestUrl;
@property(retain, nonatomic) NSURLConnection* urlConnection;
@property(retain, nonatomic) NSData* responseData;
@property(copy, nonatomic) NSString* url;
-(void)dealloc;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)processWebRequestWithURL:(id)url;
-(void)connectWithURLConnection;
@end

