/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FAADWebRequest.h"

@class FAADHttpRequest;

__attribute__((visibility("hidden")))
@interface FAADOfferClickedWebService : FAADWebRequest {
@private
	FAADHttpRequest* faadHttpRequest_;
	int currentOfferNumber_;
}
@property(assign) int currentOfferNumber;
@property(retain, nonatomic) FAADHttpRequest* faadHttpRequest;
-(void)dealloc;
-(void)reConnectedForOfferClicked:(id)offerClicked;
-(void)processErrorCode504;
-(void)requestSucceeded:(id)succeeded;
-(void)processWebRequest;
-(id)createRestFullUrlWithToken:(id)token;
-(void)sendRequestForOfferClicked;
-(void)sendRequestWithOfferNumber:(int)offerNumber;
@end

