/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface FAADLog : XXUnknownSuperclass {
@private
	int level_;
	NSString* context_;
	NSString* format_;
}
@property(assign) int level_;
@property(retain, nonatomic) NSString* format_;
@property(retain, nonatomic) NSString* context_;
+(void)logWithLevel:(int)level forMessage:(id)message;
+(void)initialize;
-(void)dealloc;
-(id)nameOfLevel:(int)level;
-(void)logAt:(int)at format:(id)format args:(void*)args;
-(void)debug:(id)debug;
-(BOOL)debugEnabled;
-(BOOL)levelEnabled:(int)enabled;
-(id)initWithContext:(id)context;
@end

