/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface FAADReachability : XXUnknownSuperclass {
@private
	BOOL _networkStatusNotificationsEnabled;
	NSString* _hostName;
	NSString* _address;
	NSMutableDictionary* _reachabilityQueries;
}
@property(assign, nonatomic) NSMutableDictionary* reachabilityQueries;
@property(retain, nonatomic) NSString* address;
@property(retain, nonatomic) NSString* hostName;
@property(assign) BOOL networkStatusNotificationsEnabled;
+(id)sharedReachability;
-(BOOL)addressFromString:(id)string address:(sockaddr_in*)address;
-(int)localWiFiConnectionStatus;
-(int)internetConnectionStatus;
-(int)remoteHostStatus;
-(SCNetworkReachabilityRef)reachabilityRefForAddress:(id)address;
-(SCNetworkReachabilityRef)reachabilityRefForHostName:(id)hostName;
-(void)stopListeningForReachabilityChanges;
-(BOOL)isNetworkAvailableFlags:(unsigned*)flags;
-(BOOL)isAdHocWiFiNetworkAvailableFlags:(unsigned*)flags;
-(BOOL)isHostReachable:(id)reachable;
-(BOOL)isReachableWithoutRequiringConnection:(unsigned)connection;
-(void)dealloc;
@end

