/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FAADWebRequest.h"

@class NSDictionary, FAADHttpRequest, NSString;

__attribute__((visibility("hidden")))
@interface FAADConnectWebService : FAADWebRequest {
@private
	FAADHttpRequest* faadHttpRequest_;
	NSString* callBackNotificationName_;
	NSString* sessionToken_;
	NSDictionary* requestParameters_;
	int isCallBack_;
	BOOL isProcessingRequest_;
}
@property(assign) BOOL isProcessingRequest;
@property(assign) int isCallBack;
@property(retain, nonatomic) NSDictionary* requestParameters;
@property(retain, nonatomic) NSString* sessionToken;
@property(retain, nonatomic) NSString* callBackNotificationName;
@property(retain, nonatomic) FAADHttpRequest* faadHttpRequest;
+(id)alloc;
+(id)sharedFAADConnectWebService;
-(void)dealloc;
-(void)connectWithCallBack:(id)callBack;
-(void)requestFailed;
-(void)processError500;
-(void)requestSucceeded:(id)succeeded;
-(void)connectWithFAADServer;
-(void)processWebRequest;
-(id)createRestFullUrlWithParameters:(id)parameters;
-(void)sendRequestWithParameter:(id)parameter;
-(id)init;
@end

