/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBLoginDialogDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, FBDialog, FBRequest, NSString, NSDate;
@protocol FBSessionDelegate;

__attribute__((visibility("hidden")))
@interface Facebook : XXUnknownSuperclass <FBLoginDialogDelegate> {
@private
	NSString* _accessToken;
	NSDate* _expirationDate;
	id<FBSessionDelegate> _sessionDelegate;
	FBRequest* _request;
	FBDialog* _loginDialog;
	FBDialog* _fbDialog;
	NSString* _appId;
	NSArray* _permissions;
}
@property(assign, nonatomic) id<FBSessionDelegate> sessionDelegate;
@property(copy, nonatomic) NSDate* expirationDate;
@property(copy, nonatomic) NSString* accessToken;
-(void)request:(id)request didFailWithError:(id)error;
-(void)fbDialogNotLogin:(BOOL)login;
-(void)fbDialogLogin:(id)login expirationDate:(id)date;
-(BOOL)isSessionValid;
-(void)dialog:(id)dialog andParams:(id)params andDelegate:(id)delegate;
-(void)dialog:(id)dialog andDelegate:(id)delegate;
-(void)requestWithGraphPath:(id)graphPath andParams:(id)params andHttpMethod:(id)method andDelegate:(id)delegate;
-(void)requestWithGraphPath:(id)graphPath andParams:(id)params andDelegate:(id)delegate;
-(void)requestWithGraphPath:(id)graphPath andDelegate:(id)delegate;
-(void)requestWithMethodName:(id)methodName andParams:(id)params andHttpMethod:(id)method andDelegate:(id)delegate;
-(void)requestWithParams:(id)params andDelegate:(id)delegate;
-(void)logout:(id)logout;
-(BOOL)handleOpenURL:(id)url;
-(void)authorize:(id)authorize delegate:(id)delegate;
-(id)parseURLParams:(id)params;
-(void)authorizeWithFBAppAuth:(BOOL)fbappAuth safariAuth:(BOOL)auth;
-(void)openUrl:(id)url params:(id)params httpMethod:(id)method delegate:(id)delegate;
-(void)dealloc;
-(id)initWithAppId:(id)appId;
@end

