/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "FBDialog.h"

@protocol FBLoginDialogDelegate;

__attribute__((visibility("hidden")))
@interface FBLoginDialog : FBDialog {
@private
	id<FBLoginDialogDelegate> _loginDelegate;
}
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)dialogDidCancel:(id)dialog;
-(void)dialogDidSucceed:(id)dialog;
-(id)initWithURL:(id)url loginParams:(id)params delegate:(id)delegate;
@end

