/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface FBLoginButton : XXUnknownSuperclass {
@private
	BOOL _isLoggedIn;
}
@property(assign, nonatomic) BOOL isLoggedIn;
-(void)updateImage;
-(id)buttonHighlightedImage;
-(id)buttonImage;
@end

