/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SingletonSoundManager;

__attribute__((visibility("hidden")))
@interface FlashScreen : XXUnknownSuperclass {
@private
	Color color;
	float alpha;
	CGRect flashRect;
	float time;
	float duration_alphaEffect;
	float duration_whiteScreen;
	SingletonSoundManager* sharedSoundManager;
	BOOL ended;
}
-(void)drawRectangle:(CGRect)rectangle red:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;
-(void)draw;
-(void)update:(float)update;
-(void)setEnd;
-(void)reset;
-(id)initWithFlashRect:(CGRect)flashRect color:(Color)color whiteScreenDuration:(float)duration alphaEffectDuration:(float)duration4;
@end

