/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol GKMatchmakerViewControllerDelegate <NSObject>
-(void)matchmakerViewController:(id)controller didFailWithError:(id)error;
-(void)matchmakerViewControllerWasCancelled:(id)cancelled;
@optional
-(void)matchmakerViewController:(id)controller didReceiveAcceptFromHostedPlayer:(id)hostedPlayer;
-(void)matchmakerViewController:(id)controller didFindPlayers:(id)players;
-(void)matchmakerViewController:(id)controller didFindMatch:(id)match;
@end

