/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSOperationQueue, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface ImageCache : XXUnknownSuperclass {
@private
	NSMutableDictionary* memCache_;
	NSOperationQueue* cacheInQueue;
	NSOperationQueue* cacheOutQueue;
}
+(id)sharedImageCache;
-(void)clearMemory;
-(void)removeImageForKey:(id)key;
-(void)imageForKey:(id)key forDelegate:(id)delegate userInfo:(id)info;
-(void)storeImage:(id)image forKey:(id)key;
-(void)dealloc;
-(id)init;
@end

