/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ImageCacheDelegate <NSObject>
@optional
-(void)imageCache:(id)cache didNotFindImageForKey:(id)key userInfo:(id)info;
-(void)imageCache:(id)cache didFindImage:(id)image forKey:(id)key userInfo:(id)info;
@end

