/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSXMLParserDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, EasyGlyph, NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface MedalStore : XXUnknownSuperclass <NSXMLParserDelegate> {
@private
	NSString* deviceType;
	NSMutableArray* medalStoreItems;
	NSMutableDictionary* medalStoreTextures;
	EasyGlyph* easyGlyph;
	NSMutableArray* ammo1Quantities;
	NSMutableArray* ammo2Quantities;
	BOOL _iPod4;
	BOOL _iPad;
	BOOL _iPadNew;
}
-(id)getMedalStoreItemForKey:(id)key;
-(id)getMedalStoreItemAtIndex:(int)index;
-(int)itemsCount;
-(id)getItemTextureForKey:(id)key;
-(id)getItemTextureAtIndex:(int)index;
-(void)refreshStore;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)parseXml:(id)xml;
-(void)populate;
-(void)detectDevice;
-(void)dealloc;
-(id)initArmyShop;
-(id)initWeapons;
@end

