/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MedalStoreItem : XXUnknownSuperclass {
@private
	NSString* name;
	NSString* title;
	NSString* desc;
	NSString* type;
	int om;
	int weaponId;
	int ammo1;
	int ammo2;
	BOOL bought;
	BOOL consumable;
	CGPoint offset;
	float scale;
	float boughtTimeout;
}
@property(assign, nonatomic) float scale;
@property(assign, nonatomic) CGPoint offset;
@property(assign, nonatomic) BOOL consumable;
@property(assign, nonatomic) BOOL bought;
@property(assign, nonatomic) int ammo2;
@property(assign, nonatomic) int ammo1;
@property(assign, nonatomic) int weaponId;
@property(assign, nonatomic) int om;
@property(retain, nonatomic) NSString* type;
@property(retain, nonatomic) NSString* desc;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* name;
-(void)update;
-(float)boughtTimeout;
-(BOOL)buy;
-(void)refresh;
-(id)initWithName:(id)name title:(id)title desc:(id)desc medals:(int)medals type:(id)type;
@end

