/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "UIScrollViewDelegate.h"
#import "NSXMLParserDelegate.h"
#import "MultiplayerInvitationReceiver.h"
#import "FBRequestDelegate.h"
#import "Overkill-Structs.h"
#import "FBDialogDelegate.h"
#import "FBSessionDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SKRequest, SKProductsRequest, Options, SingletonSoundManager, NSString, NSArray, Texture2D, NSMutableDictionary, EasyGlyph, ExperienceBar, NSMutableArray, Endround, SingletonTextureManager, DailySurprise, MedalStore, UIScrollView, Facebook, UIActivityIndicatorView, Killpedia, UIViewController;

__attribute__((visibility("hidden")))
@interface MenuView : XXUnknownSuperclass <UIScrollViewDelegate, NSXMLParserDelegate, FBRequestDelegate, FBDialogDelegate, FBSessionDelegate, UITextFieldDelegate, MultiplayerInvitationReceiver> {
@private
	SingletonTextureManager* sharedTextureManager;
	BOOL goToMainmenu;
	int outto;
	int loadedPercent;
	BOOL _iPad;
	BOOL _iPod4;
	BOOL _iPadNew;
	float dTime;
	Texture2D* _textureAwards[5];
	Texture2D* _textureMenu[10];
	Texture2D* _textureStore[43];
	Texture2D* _textureTips[3];
	Texture2D* _multiplayerTextures[5];
	CGPoint screenShift;
	CGPoint deviceTranslate;
	float ratio;
	float deviceScale;
	float retinaScale;
	NSString* deviceType;
	UIScrollView* awardScroll;
	EasyGlyph* easyGlyph;
	NSMutableDictionary* dTexts;
	NSMutableDictionary* dAwards;
	NSMutableDictionary* dStore;
	NSMutableDictionary* dNumbers;
	int _state;
	int _awardTab;
	int _storeTab;
	NSMutableDictionary* dEffects;
	NSString* tabName;
	int xmlAwardTypeCounter[4];
	int xmlAwardTypeFinished[4];
	NSString* xmlAwardTypeName;
	int awardScrollWidth;
	CGPoint awardScrollOffset;
	CGPoint touchStarted;
	CGPoint touchEnded;
	float scrollingSpeed;
	bool scrollTouching;
	ExperienceBar* bar;
	Endround* endround;
	int totalScore;
	CGPoint tapPosition;
	float tapTime;
	BOOL showLoading;
	int armyItemPressed;
	MedalStore* medalStore;
	int buyingItemId;
	NSMutableArray* aTips;
	NSMutableArray* aTipsHeight;
	NSMutableArray* aStatsLeft;
	NSMutableArray* aStatsRight;
	SKRequest* _skRequest;
	SKProductsRequest* _skProductReq;
	int buyingPack;
	UIActivityIndicatorView* spinner;
	BOOL iapSpinnerShowing;
	NSMutableArray* aMenuTextures;
	int menuButtonClicked;
	Facebook* _facebook;
	NSArray* _permissions;
	NSString* code;
	int codePromotion;
	UIViewController* myController;
	SingletonSoundManager* sharedSoundManager;
	Options* options;
	Texture2D* tipsPage_texture;
	int tipsPage_count;
	int tipsPage_counter;
	float tapJoyLogo_scale;
	float tapJoyLogo_scale_inverter;
	BOOL _screenRotated;
	Killpedia* killpedia;
	BOOL killpediaShowing;
	int killpediaWillShow;
	NSMutableArray* badgeTextures;
	float infoArrow_offset;
	int textField_currentRotation;
	DailySurprise* dailySurprise;
}
@property(assign, nonatomic) int state;
-(void)inviteAlert;
-(void)inviteReceived;
-(void)launchMailAppOnDevice;
-(void)dialogDidComplete:(id)dialog;
-(void)request:(id)request didLoad:(id)load;
-(void)request:(id)request didReceiveResponse:(id)response;
-(void)setScreenRotation:(BOOL)rotation;
-(void)hideSpinner;
-(void)updateMedals:(int)medals;
-(int)outto;
-(BOOL)showLoading;
-(void)setShowLoading:(BOOL)loading;
-(BOOL)goToMainmenu;
-(BOOL)isInRect:(CGRect)rect point:(CGPoint)point raw:(BOOL)raw;
-(void)accelerometer:(id)accelerometer didAccelerate:(id)accelerate;
-(void)connectionUnreachableAlert;
-(void)showLeaderboard;
-(void)showAchievements;
-(void)createTextField;
-(void)checkingDeviceOrientation;
-(void)publishStream;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(CGPoint)setTouchLocation:(CGPoint)location;
-(void)touchesEnded:(id)ended withEvent:(id)event withView:(id)view;
-(void)touchesMoved:(id)moved withEvent:(id)event withView:(id)view;
-(void)touchesBegan:(id)began withEvent:(id)event withView:(id)view;
-(void)drawNumber:(CGPoint)number number:(int)number2 offset:(float)offset;
-(void)drawArmyStoreItem:(int)item atPosition:(CGPoint)position;
-(void)changeTabTo:(int)to;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
-(void)parseXml:(id)xml;
-(void)drawNumber:(int)number atOffset:(CGPoint)offset scale:(float)scale;
-(void)drawMultidigitNumber:(int)number position:(CGPoint)position alignment:(int)alignment r:(float)r g:(float)g b:(float)b alpha:(float)alpha scale:(float)scale nofDigit:(int)digit digitOffset:(int)offset zerofill:(BOOL)zerofill showPlus:(BOOL)plus showMinus:(BOOL)minus;
-(void)drawRect:(CGRect)rect withAngle:(float)angle fillColor:(Color4f)color;
-(void)drawRect:(CGRect)rect fillColor:(Color4f)color;
-(void)placeTexture:(id)texture translate:(CGPoint)translate rotate:(float)rotate scale:(CGPoint)scale alignment:(int)alignment color:(Color4f)color;
-(void)placeTexture:(id)texture translate:(CGPoint)translate rotate:(float)rotate scale:(CGPoint)scale;
-(void)placeTexture:(id)texture translate:(CGPoint)translate;
-(void)placeTexture:(id)texture translate:(CGPoint)translate rotate:(float)rotate;
-(void)placeTexture:(id)texture translate:(CGPoint)translate scale:(CGPoint)scale;
-(void)drawTabNumberAtPosition:(CGPoint)position tabName:(int)name;
-(void)drawAwardBarGamut:(CGPoint)gamut percent:(int)percent row:(int)row;
-(void)drawAwardBar:(CGPoint)bar row:(int)row;
-(void)drawView;
-(void)loadStats;
-(void)loadTextures:(int)textures;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)setupAwardScroll;
-(id)platform;
-(void)detectDevice;
-(id)myHash:(id)hash;
-(void)doStuff;
-(void)unloadTextures:(int)textures;
-(int)loadedPercent;
-(void)dealloc;
@end

