/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextFieldDelegate.h"

@class NSMutableData, Chat, NSString, UITextField;

__attribute__((visibility("hidden")))
@interface MultiplayerTextField : XXUnknownSuperclass <UITextFieldDelegate> {
@private
	UITextField* _textField;
	CGAffineTransform transformFlip;
	Chat* chat;
	CGAffineTransform transformDidBeginEditing;
	CGAffineTransform transformDidEndEditing;
	NSString* previousText;
	BOOL typing;
	float typing_timeToEnd;
	float dTime;
	int previousOrientation;
	NSMutableData* receivedData;
	NSString* baseText;
}
-(void)setBaseText:(id)text;
-(void)setChat:(id)chat;
-(void)destroyTextField;
-(void)textFieldEndEditing;
-(void)clearTextField;
-(id)textFieldValue;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)setTransformDidBeginEditing:(CGPoint)beginEditing;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)getOnlineDataFromBadWordsFilter:(id)badWordsFilter;
-(void)checkTyping;
-(BOOL)isTyping;
-(void)setdTime:(float)time;
-(void)activateKeyboard;
-(void)createTextField:(CGRect)field fontSize:(float)size rotation:(float)rotation;
@end

