/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface MultiplayerInvitedPlayersList : XXUnknownSuperclass {
@private
	NSString* localPlayerID;
	NSMutableDictionary* list;
	int nextPlayerCountWhenAddOm;
}
-(unsigned long long)getCRC;
-(void)loadForLocalPlayerID:(id)localPlayerID;
-(void)save;
-(void)increaseNextPlayerCountWhenAddOm;
-(int)nextPlayerCountWhenAddOm;
-(void)printInvitedList;
-(int)countOfPlayersInInvitedList;
-(void)addPlayerToInvitedList:(id)invitedList;
-(bool)isPlayerInInvitedList:(id)invitedList;
@end

