/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Multiplayer_WeaponsData : XXUnknownSuperclass {
@private
	WeaponCfg weapons;
	int winsToNextUpgrade;
	BOOL allUpgradeBought;
}
+(id)sharedMultiplayerWeaponsData;
-(void)setAllUpgradeBought:(BOOL)bought;
-(BOOL)isAllUpgradesBought;
-(void)setWinsToNextUpgrade:(int)nextUpgrade;
-(int)nextWeaponUpgradeForWinsInTier:(int)tier;
-(void)loadWeapon:(int)weapon;
-(void)saveWeapon:(int)weapon;
-(void)setWeapon:(WeaponCfg)weapon;
-(WeaponCfg)weapon;
-(id)init;
@end

