/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSMutableData, NSURLConnection;
@protocol NBSImageDownloaderDelegate;

__attribute__((visibility("hidden")))
@interface NBSImageDownloader : XXUnknownSuperclass {
@private
	NSURL* urlString_;
	id<NBSImageDownloaderDelegate> delegate_;
	NSURLConnection* connection;
	NSMutableData* imageData;
	id userInfo;
	BOOL isCancel;
}
@property(retain, nonatomic) id userInfo;
@property(retain, nonatomic) NSMutableData* imageData;
@property(retain, nonatomic) NSURLConnection* connection;
@property(assign) id delegate_;
@property(copy) NSURL* urlString_;
+(id)downloaderWithURL:(id)url delegate:(id)delegate userInfo:(id)info;
+(id)downloaderWithURL:(id)url delegate:(id)delegate;
-(void)dealloc;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)cancelDownload;
-(void)startDownload;
@end

