/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NBSImageDownloaderDelegate.h"
#import "ImageCacheDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface NBSImageManager : XXUnknownSuperclass <NBSImageDownloaderDelegate, ImageCacheDelegate> {
@private
	NSMutableArray* delegates_;
	NSMutableArray* downloaders_;
	NSMutableDictionary* urlDownloaders_;
	NSMutableArray* failedUrls_;
}
+(id)sharedManager;
-(void)imageDownloader:(id)downloader didFailWithError:(id)error;
-(void)imageDownloader:(id)downloader didFinishWithImage:(id)image;
-(void)imageCache:(id)cache didNotFindImageForKey:(id)key userInfo:(id)info;
-(void)imageCache:(id)cache didFindImage:(id)image forKey:(id)key userInfo:(id)info;
-(void)downloadImageFromURL:(id)url delegate:(id)delegate retryFailed:(BOOL)failed;
-(void)downloadImageFromURL:(id)url delegate:(id)delegate;
-(void)dealloc;
-(id)init;
@end

