/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol NBSImageDownloaderDelegate <NSObject>
@optional
-(void)imageDownloader:(id)downloader didFailWithError:(id)error;
-(void)imageDownloader:(id)downloader didFinishWithImage:(id)image;
-(void)imageDownloaderDidFinish:(id)imageDownloader;
@end

