/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextViewDelegate.h"
#import "Overkill-Structs.h"
#import "UIWebViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableData, UITextView, UIWebView, NSString, Facebook, UIImageView, UIButton, UIView, NSArray, UIActivityIndicatorView, UIWindow;

__attribute__((visibility("hidden")))
@interface NewsViewController : XXUnknownSuperclass <UITextViewDelegate, UIWebViewDelegate> {
@private
	UIWindow* mainWindow;
	UIWebView* mainWebView;
	UIImageView* mainView;
	UIButton* exitBtn;
	UIButton* mainButton;
	int badgeNumber;
	NSMutableData* receivedData;
	UITextView* tfContestMain;
	UITextView* tfContestText;
	UITextView* tfFacebookSite;
	NSString* contestText;
	UIButton* btnLike;
	UIButton* btnBack;
	UIButton* btnFacebook;
	UIButton* btnEmail;
	UIButton* btnTwitter;
	UIView* facebookLikeView;
	UIWebView* webView;
	Facebook* _facebook;
	NSString* kAppId;
	NSArray* _permissions;
	NSString* facebookSite;
	BOOL contest;
	NSString* deviceType;
	CGPoint deviceSize;
	UIActivityIndicatorView* spinner;
}
@property(retain, nonatomic) UIButton* btnEmail;
@property(retain, nonatomic) UIButton* btnTwitter;
@property(retain, nonatomic) UIButton* btnFacebook;
@property(retain, nonatomic) UIButton* btnBack;
@property(retain, nonatomic) UIButton* btnLike;
@property(retain, nonatomic) UITextView* tfFacebookSite;
@property(retain, nonatomic) UITextView* tfContestText;
@property(retain, nonatomic) UITextView* tfContestMain;
+(id)sharedNewsView;
-(id).cxx_construct;
-(int)badgeNumber;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)hideSpinner;
-(void)showSpinner:(CGPoint)spinner;
-(void)webViewDidFinishLoad:(id)webView;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)backToGame;
-(void)connectForNews;
-(void)setMainWindows:(bool)windows;
@end

