/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, OAMutableURLRequest, NSError, NSHTTPURLResponse, NSURLConnection;

__attribute__((visibility("hidden")))
@interface OADataFetcher : XXUnknownSuperclass {
@private
	OAMutableURLRequest* request;
	NSHTTPURLResponse* response;
	NSURLConnection* connection;
	NSError* error;
	NSData* responseData;
	id delegate;
	SEL didFinishSelector;
	SEL didFailSelector;
}
-(void)fetchDataWithRequest:(id)request delegate:(id)delegate didFinishSelector:(SEL)selector didFailSelector:(SEL)selector4;
@end

