/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OASignatureProviding.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface OAHMAC_SHA1SignatureProvider : XXUnknownSuperclass <OASignatureProviding> {
}
-(id)signClearText:(id)text withSecret:(id)secret;
-(id)name;
@end

