/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, OAConsumer, NSString, OAToken;
@protocol OASignatureProviding;

__attribute__((visibility("hidden")))
@interface OAMutableURLRequest : XXUnknownSuperclass {
@private
	OAConsumer* consumer;
	OAToken* token;
	NSString* realm;
	NSString* signature;
	id<OASignatureProviding> signatureProvider;
	NSString* nonce;
	NSString* timestamp;
	NSMutableDictionary* extraOAuthParameters;
	BOOL didPrepare;
}
@property(readonly, assign) NSString* nonce;
@property(readonly, assign) NSString* signature;
-(id)_signatureBaseString;
-(void)_generateNonce;
-(void)_generateTimestamp;
-(void)prepare;
-(void)setOAuthParameterName:(id)name withValue:(id)value;
-(void)dealloc;
-(id)initWithURL:(id)url consumer:(id)consumer token:(id)token realm:(id)realm signatureProvider:(id)provider nonce:(id)nonce timestamp:(id)timestamp;
-(id)initWithURL:(id)url consumer:(id)consumer token:(id)token realm:(id)realm signatureProvider:(id)provider;
@end

