/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface OARequestParameter : XXUnknownSuperclass {
@private
	NSString* name;
	NSString* value;
}
@property(retain) NSString* value;
@property(retain) NSString* name;
+(id)requestParameterWithName:(id)name value:(id)value;
-(id)URLEncodedNameValuePair;
-(id)URLEncodedValue;
-(id)URLEncodedName;
-(void)dealloc;
-(id)initWithName:(id)name value:(id)value;
@end

