/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class OAMutableURLRequest, NSData, NSString, NSHTTPURLResponse;

__attribute__((visibility("hidden")))
@interface OAServiceTicket : XXUnknownSuperclass {
@private
	OAMutableURLRequest* request;
	NSHTTPURLResponse* response;
	NSData* data;
	BOOL didSucceed;
}
@property(readonly, assign) NSString* body;
@property(readonly, assign) BOOL didSucceed;
@property(readonly, assign) NSData* data;
@property(readonly, assign) NSHTTPURLResponse* response;
@property(readonly, assign) OAMutableURLRequest* request;
-(id)initWithRequest:(id)request response:(id)response data:(id)data didSucceed:(BOOL)succeed;
-(id)initWithRequest:(id)request response:(id)response didSucceed:(BOOL)succeed;
@end

