/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface OAToken : XXUnknownSuperclass {
@private
	NSString* key;
	NSString* secret;
	NSString* sessionHandle;
}
@property(retain) NSString* sessionHandle;
@property(retain) NSString* secret;
@property(retain) NSString* key;
-(int)storeInUserDefaultsWithServiceProviderName:(id)serviceProviderName prefix:(id)prefix;
-(void)dealloc;
-(id)initWithUserDefaultsUsingServiceProviderName:(id)userDefaultsUsingServiceProviderName prefix:(id)prefix;
-(id)initWithHTTPResponseBody:(id)httpresponseBody;
-(id)initWithKey:(id)key secret:(id)secret;
-(id)init;
@end

