/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

 // Unknown library

@class NSString, NSMutableArray;


typedef struct Color4 {
	float r;
	float g;
	float b;
	float a;
} Color4;

@interface Obstacle : NSObject {
@private
	CGRect rect;
	CGPoint3f position;
	CGPoint3f texturePosition;
	CGPoint3f lowestPoint;
	CGPoint3f polygons[30][100];
	CGPoint3f newPathIndex[40];
	CGPoint3f obstacleInput;
	CGPoint3f obstacleOutput;
	CGPoint3f bypassPath[40];
	int polygonIndex;
	int pointIndex[30];
	int pathInfo[3];
	int pathIndex;
	int nearestInputVertexIndex;
	int nearestOutputVertexIndex;
	BOOL inObstacle;
	BOOL rearrangedPath;
	BOOL drawTexture;
	NSString* textureKey;
	int zindex;
	NSString* name;
	int polygonMaterial[30];
	int affectedMaterial;
	Color4 polygonColor[30];
	float alpha;
	float scale;
	float explosionScale;
	int obstacleType;
	NSMutableArray* textureAnimation;
	float dTime;
	int animationFrame;
	float animationTime;
	float frameLenght;
	BOOL rotating;
	float angle;
	float rotatingSpeed;
}
//-(id).cxx_construct;
-(void)setRotatingSpeed:(float)speed;
-(float)angle;
-(BOOL)isRotating;
-(void)setRotating:(BOOL)rotating;
-(void)setFrameLenght:(float)lenght;
-(void)setDTime:(float)time;
-(void)addTextureAnimationName:(id)name;
-(float)explosionScale;
-(void)setExplosionScale:(float)scale;
-(int)getPathWay;
-(int)getStopIndex;
-(int)getStartIndex;
-(BOOL)hasRearrangedPath;
-(void)setRearrangedPath:(BOOL)path;
-(void)setWasInObstacle:(BOOL)obstacle;
-(BOOL)wasInObstacle;
-(float)distanceFromPoint:(CGPoint3f)point toPoint:(CGPoint3f)point2;
-(int)insidePolygon:(int)polygon collisionPoint:(CGPoint3f)point onBound:(int)bound;
-(int)affectedMaterial;
-(void)affectedMaterial:(int)material;
-(int)insideObstacle:(CGPoint3f)obstacle onBound:(int)bound;
-(void)drawPolygon:(CGPoint3f [100])polygon vertexCount:(int)count fillColor:(Color4)color;
-(void)draw;
-(CGPoint3f)position3f;
-(void)setPosition:(CGPoint3f)position;
-(void)addPolygon:(float [100])polygon nofValues:(int)values nofPointValues:(int)values3 ofMaterial:(int)material withColor:(Color4)color;
-(void)addPolygon:(float [100])polygon nofValues:(int)values nofPointValues:(int)values3 ofMaterial:(int)material;
-(int)zindex;
-(void)setZindex:(int)zindex;
-(BOOL)shouldDrawTexture;
-(float)getScale;
-(float)alpha;
-(CGPoint3f)texturePosition;
-(id)textureName;
-(void)setTexture:(id)texture atPoint:(CGPoint3f)point alpha:(float)alpha scale:(float)scale drawTexture:(BOOL)texture5;
-(id)name;
-(BOOL)isImaginary;
-(int)obstacleType;
-(void)obstacleType:(int)type;
-(void)updateTextureAnimation;
-(id)initAtPosition:(CGPoint3f)position;
-(id)initWithName:(id)name;
-(id)initAsPoly;
-(CGRect)rectangle;
-(id)initAsRect:(CGRect)rect;
-(void)dealloc;
@end

