/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface OpenUDID : XXUnknownSuperclass {
}
+(int)getOpenUDIDSlotCount;
+(id)valueWithError:(id*)error;
+(id)value;
+(id)_getOpenUDID;
+(id)_getDictFromPasteboard:(id)pasteboard;
+(void)_setDict:(id)dict forPasteboard:(id)pasteboard;
@end

