/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Drawable.h"
#import "Overkill-Structs.h"

@class EasyGlyph, SingletonSoundManager, Texture2D;

__attribute__((visibility("hidden")))
@interface Options : Drawable {
@private
	BOOL ingame;
	EasyGlyph* font;
	Texture2D* _texture[18];
	float soundVolume;
	float musicVolume;
	BOOL options_blood;
	BOOL options_autoswitch;
	BOOL options_crosshair;
	float options_joystickSensitivity;
	int movingWith;
	float iPodScale;
	SingletonSoundManager* sharedSoundManager;
	BOOL showCredits;
}
-(void)touchesEnded:(CGPoint)ended;
-(void)touchesMoved:(CGPoint)moved;
-(void)touchesBegan:(CGPoint)began;
-(void)drawSwitcherAt:(CGPoint)at value:(BOOL)value texture:(id)texture;
-(void)drawDotsAt:(CGPoint)at count:(int)count offset:(float)offset;
-(void)draw;
-(void)dealloc;
-(id)initOptions:(BOOL)options withFont:(id)font withBackground:(id)background;
@end

