/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "Foundation.h"

@class NSMutableDictionary, WeaponsCampView, SingletonSoundManager;

__attribute__((visibility("hidden")))
@interface Particle : Foundation {
@private
	WeaponsCampView* weaponsCamp;
	int fromIndex;
	int framesCount;
	int stayAtIndex;
	int drawingMethod;
	float delay;
	float alfa;
	CGPoint offset;
	int frame;
	float time;
	float frameDuration;
	float muzzle_time;
	float muzzle_waiting;
	BOOL ended;
	BOOL isFrameSet;
	BOOL timeToShow;
	float dSpeed;
	int fromFrame;
	int toFrame;
	float fromAlpha;
	float toAlpha;
	float alphaPerFrame;
	SingletonSoundManager* sharedSoundManager;
	int type;
	NSMutableDictionary* dTargetTexNames;
}
-(id).cxx_construct;
-(float)alpha;
-(id)name;
-(int)getType;
-(BOOL)isEnded;
-(id)texture;
-(CGPoint)position;
-(int)getFrame;
-(int)frame;
-(void)setFramesCounter:(int)counter;
-(void)setFrame:(int)frame duration:(float)duration;
-(void)updateMuzzle;
-(void)startDrawMuzzelFromFrame:(int)frame toFrame:(int)frame2 duration:(float)duration;
-(void)setAlphaPerFrame:(float)frame;
-(void)drawMuzzleWithTarget:(id)target;
-(void)drawTargetWithOutline:(BOOL)outline iPod4:(BOOL)a4;
-(void)updateTarget;
-(void)setFrame:(int)frame;
-(void)setFromAlpha:(float)alpha toAlpha:(float)alpha2;
-(void)drawBloodScreen;
-(void)updateBloodScreen;
-(void)drawParticle;
-(void)updateParticle;
-(void)dealloc;
-(id)initAtPosition:(CGPoint)position offset:(CGPoint)offset angle:(float)angle fromIndex:(int)index frames:(int)frames stayAtIndex:(int)index6 delay:(float)delay drawingMethod:(int)method parentclass:(id)parentclass;
-(id)initBloodScreenParticle:(id)particle position:(CGPoint)position offset:(CGPoint)offset scale:(float)scale angle:(float)angle frames:(int)frames showFrame:(int)frame fromAlpha:(float)alpha toAlpha:(float)alpha9 alphaPerFrame:(float)frame10 textureDictionary:(id)dictionary parentclass:(id)parentclass;
-(id)initWithParticle:(id)particle type:(int)type position:(CGPoint)position offset:(CGPoint)offset scale:(float)scale angle:(float)angle color:(Color)color fromIndex:(int)index frames:(int)frames stayAtIndex:(int)index10 delay:(float)delay textureDictionary:(id)dictionary parentclass:(id)parentclass;
-(id)initWithParticle:(id)particle type:(int)type position:(CGPoint)position offset:(CGPoint)offset scale:(float)scale angle:(float)angle fromIndex:(int)index frames:(int)frames stayAtIndex:(int)index9 delay:(float)delay textureDictionary:(id)dictionary parentclass:(id)parentclass;
-(id)initWithTargetParticle:(id)targetParticle type:(int)type position:(CGPoint)position offset:(CGPoint)offset scale:(float)scale angle:(float)angle fromIndex:(int)index frames:(int)frames stayAtIndex:(int)index9 delay:(float)delay textureDictionary:(id)dictionary dTargetTexNames:(id)names parentclass:(id)parentclass;
@end

