/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface PVRTexture : XXUnknownSuperclass {
@private
	NSMutableArray* _imageData;
	unsigned _name;
	unsigned _width;
	unsigned _height;
	unsigned _internalFormat;
	BOOL _hasAlpha;
}
@property(readonly, assign) BOOL hasAlpha;
@property(readonly, assign) unsigned internalFormat;
@property(readonly, assign) unsigned height;
@property(readonly, assign) unsigned width;
@property(readonly, assign) unsigned name;
+(id)pvrTextureWithContentsOfURL:(id)url;
+(id)pvrTextureWithContentsOfFile:(id)file;
-(void)dealloc;
-(id)initWithContentsOfURL:(id)url;
-(id)initWithContentsOfFile:(id)file;
-(BOOL)createGLTexture:(id)texture;
-(BOOL)unpackPVRData:(id)data;
-(void)drawVertices:(float*)vertices verticesCount:(int)count texWidth:(float)width texHeight:(float)height textures:(int)textures;
-(void)drawAtPoint:(CGPoint)point;
-(void)drawInRect:(CGRect)rect;
@end

