/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBJson3StreamParserDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSMutableArray;
@protocol SBJson3StreamParserAdapterDelegate;

__attribute__((visibility("hidden")))
@interface SBJson3StreamParserAdapter : XXUnknownSuperclass <SBJson3StreamParserDelegate> {
@private
	id<SBJson3StreamParserAdapterDelegate> delegate;
	unsigned levelsToSkip;
	unsigned depth;
	NSMutableArray* array;
	NSMutableDictionary* dict;
	NSMutableArray* keyStack;
	NSMutableArray* stack;
	int currentType;
}
@property(assign) id<SBJson3StreamParserAdapterDelegate> delegate;
@property(assign) unsigned levelsToSkip;
-(void)parser:(id)parser foundString:(id)string;
-(void)parser:(id)parser foundNumber:(id)number;
-(void)parserFoundNull:(id)null;
-(void)parser:(id)parser foundBoolean:(BOOL)boolean;
-(void)parserFoundArrayEnd:(id)end;
-(void)parserFoundArrayStart:(id)start;
-(void)parserFoundObjectEnd:(id)end;
-(void)parser:(id)parser foundObjectKey:(id)key;
-(void)parserFoundObjectStart:(id)start;
-(void)parser:(id)parser found:(id)found;
-(void)pop;
-(void)dealloc;
-(id)init;
@end

