/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBJson3StreamWriterState, NSString, NSMutableArray;
@protocol SBJson3StreamWriterDelegate;

__attribute__((visibility("hidden")))
@interface SBJson3StreamWriter : XXUnknownSuperclass {
@private
	NSString* error;
	NSMutableArray* stateStack;
	SBJson3StreamWriterState* state;
	id<SBJson3StreamWriterDelegate> delegate;
	unsigned maxDepth;
	BOOL sortKeys;
	BOOL humanReadable;
}
@property(copy) NSString* error;
@property(assign) BOOL sortKeys;
@property(assign) BOOL humanReadable;
@property(assign) unsigned maxDepth;
@property(assign) id<SBJson3StreamWriterDelegate> delegate;
@property(readonly, assign, nonatomic) NSMutableArray* stateStack;
@property(assign, nonatomic) SBJson3StreamWriterState* state;
+(void)initialize;
-(BOOL)writeNumber:(id)number;
-(BOOL)writeString:(id)string;
-(BOOL)writeValue:(id)value;
-(BOOL)writeBool:(BOOL)aBool;
-(BOOL)writeNull;
-(BOOL)writeArrayClose;
-(BOOL)writeArrayOpen;
-(BOOL)writeObjectClose;
-(BOOL)writeObjectOpen;
-(BOOL)writeArray:(id)array;
-(BOOL)writeObject:(id)object;
-(void)appendBytes:(const void*)bytes length:(unsigned)length;
-(void)dealloc;
-(id)init;
@end

