/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBJson3StreamParserState, SBJson3Tokeniser, NSString, NSMutableArray;
@protocol SBJson3StreamParserDelegate;

__attribute__((visibility("hidden")))
@interface SBJson3StreamParser : XXUnknownSuperclass {
@private
	BOOL supportMultipleDocuments;
	id<SBJson3StreamParserDelegate> delegate;
	SBJson3Tokeniser* tokeniser;
	NSMutableArray* stateStack;
	SBJson3StreamParserState* state;
	unsigned maxDepth;
	NSString* error;
}
@property(copy) NSString* error;
@property(assign) unsigned maxDepth;
@property(assign) id<SBJson3StreamParserDelegate> delegate;
@property(assign) BOOL supportMultipleDocuments;
@property(readonly, assign, nonatomic) NSMutableArray* stateStack;
@property(assign, nonatomic) SBJson3StreamParserState* state;
-(int)parse:(id)parse;
-(void)handleArrayStart;
-(void)handleObjectStart;
-(void)maxDepthError;
-(id)tokenName:(int)name;
-(void)dealloc;
-(id)init;
@end

