/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBJson3StreamParserState.h"


__attribute__((visibility("hidden")))
@interface SBJson3StreamParserStateComplete : SBJson3StreamParserState {
}
+(id)sharedInstance;
-(int)parserShouldReturn:(id)parser;
-(id)name;
@end

