/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBJson3StreamWriterStateObjectStart.h"


__attribute__((visibility("hidden")))
@interface SBJson3StreamWriterStateObjectKey : SBJson3StreamWriterStateObjectStart {
}
+(id)sharedInstance;
-(void)appendSeparator:(id)separator;
@end

