/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBJson3Writer : XXUnknownSuperclass {
@private
	NSString* error;
	unsigned maxDepth;
	BOOL sortKeys;
	BOOL humanReadable;
}
@property(assign) BOOL sortKeys;
@property(assign) BOOL humanReadable;
@property(copy) NSString* error;
@property(assign) unsigned maxDepth;
-(id)dataWithObject:(id)object;
-(id)stringWithObject:(id)object error:(id*)error;
-(id)stringWithObject:(id)object;
-(void)dealloc;
-(id)init;
@end

