/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBJson3StreamParserAdapterDelegate.h"


__attribute__((visibility("hidden")))
@interface SBJson3StreamParserAccumulator : XXUnknownSuperclass <SBJson3StreamParserAdapterDelegate> {
@private
	id value;
}
@property(readonly, assign) id value;
-(void)parser:(id)parser foundObject:(id)object;
-(void)parser:(id)parser foundArray:(id)array;
-(void)dealloc;
@end

