/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBJson3Parser : XXUnknownSuperclass {
@private
	NSString* error;
	unsigned depth;
	unsigned maxDepth;
}
@property(copy) NSString* error;
@property(assign) unsigned maxDepth;
-(id)objectWithString:(id)string error:(id*)error;
-(id)objectWithString:(id)string;
-(id)objectWithData:(id)data;
-(void)dealloc;
-(id)init;
@end

