/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SBJson3UTF8Stream;

__attribute__((visibility("hidden")))
@interface SBJson3Tokeniser : XXUnknownSuperclass {
@private
	SBJson3UTF8Stream* _stream;
	NSString* _error;
}
@property(copy) NSString* error;
-(int)getToken:(id*)token;
-(int)getNumberToken:(id*)token;
-(int)getStringToken:(id*)token;
-(BOOL)decodeHexQuad:(unsigned short*)quad;
-(BOOL)decodeEscape:(unsigned short)escape into:(unsigned short*)into;
-(int)match:(const char*)match length:(unsigned)length retval:(int)retval;
-(void)appendData:(id)data;
-(void)dealloc;
-(id)init;
@end

