/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBJson3StreamParserState : XXUnknownSuperclass {
}
+(id)sharedInstance;
-(id)name;
-(BOOL)needKey;
-(void)parser:(id)parser shouldTransitionTo:(int)to;
-(int)parserShouldReturn:(id)parser;
-(BOOL)parser:(id)parser shouldAcceptToken:(int)token;
@end

