/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"

@class NSMutableData;

__attribute__((visibility("hidden")))
@interface SBJson3UTF8Stream : XXUnknownSuperclass {
@private
	const char* _bytes;
	NSMutableData* _data;
	unsigned _length;
	unsigned _index;
}
@property(assign) unsigned index;
-(id)stringWithRange:(NSRange)range;
-(BOOL)skipCharacters:(const char*)characters length:(unsigned)length;
-(BOOL)haveRemainingCharacters:(unsigned)characters;
-(void)skipWhitespace;
-(void)skip;
-(BOOL)getRetainedStringFragment:(id*)fragment;
-(BOOL)getNextUnichar:(unsigned short*)unichar;
-(BOOL)getUnichar:(unsigned short*)unichar;
-(void)appendData:(id)data;
-(void)dealloc;
-(id)init;
@end

