/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBJson3StreamWriterState.h"


__attribute__((visibility("hidden")))
@interface SBJson3StreamWriterStateComplete : SBJson3StreamWriterState {
}
+(id)sharedInstance;
-(BOOL)isInvalidState:(id)state;
@end

