/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ScoreEffect : XXUnknownSuperclass {
@private
	NSMutableArray* effectsArray;
	CGPoint position;
	int score;
	int place;
	BOOL ended;
	BOOL headShot;
	Color color;
}
-(id).cxx_construct;
-(Color)getColor;
-(BOOL)headShot;
-(int)place;
-(void)setPlace:(int)place;
-(int)score;
-(void)setScore:(int)score;
-(CGPoint)position;
-(void)setPosition:(CGPoint)position;
-(id)effectArray;
-(BOOL)ended;
-(void)update;
-(void)dealloc;
-(id)initWithScore:(int)score headShot:(BOOL)shot position:(CGPoint)position color:(Color)color effectsArray:(id)array;
@end

