/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSOperationQueue, UIViewController;

__attribute__((visibility("hidden")))
@interface SHK : XXUnknownSuperclass {
@private
	UIViewController* rootViewController;
	UIViewController* currentView;
	UIViewController* pendingView;
	BOOL isDismissingView;
	NSOperationQueue* offlineQueue;
}
@property(retain, nonatomic) NSOperationQueue* offlineQueue;
@property(assign) BOOL isDismissingView;
@property(retain, nonatomic) UIViewController* pendingView;
@property(retain, nonatomic) UIViewController* currentView;
@property(assign, nonatomic) UIViewController* rootViewController;
+(BOOL)connected;
+(id)error:(id)error;
+(void)flushOfflineQueue;
+(BOOL)addToOfflineQueue:(id)offlineQueue forSharer:(id)sharer;
+(void)saveOfflineQueueList:(id)list;
+(id)getOfflineQueueList;
+(id)offlineQueueListPath;
+(id)offlineQueuePath;
+(id)sharersDictionary;
+(void)logoutOfService:(id)service;
+(void)logoutOfAll;
+(void)removeAuthValueForKey:(id)key forSharer:(id)sharer;
+(void)setAuthValue:(id)value forKey:(id)key forSharer:(id)sharer;
+(id)getAuthValueForKey:(id)key forSharer:(id)sharer;
+(void)setUserExclusions:(id)exclusions;
+(id)getUserExclusions;
+(void)setFavorites:(id)favorites forType:(int)type;
+(void)pushOnFavorites:(id)favorites forType:(int)type;
+(id)favoriteSharersForType:(int)type;
+(int)modalTransitionStyle;
+(int)modalPresentationStyle;
+(int)barStyle;
+(void)setRootViewController:(id)controller;
+(void)initialize;
+(id)currentHelper;
-(id)getTopViewController;
-(void)viewWasDismissed;
-(void)showPendingView;
-(void)hideCurrentViewControllerAnimated:(BOOL)animated;
-(void)hideCurrentViewController;
-(void)showViewController:(id)controller;
-(void)dealloc;
@end

