/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface SHKActivityIndicator : XXUnknownSuperclass {
@private
	UILabel* centerMessageLabel;
	UILabel* subMessageLabel;
	UIActivityIndicatorView* spinner;
}
@property(retain, nonatomic) UIActivityIndicatorView* spinner;
@property(retain, nonatomic) UILabel* subMessageLabel;
@property(retain, nonatomic) UILabel* centerMessageLabel;
+(id)currentIndicator;
-(void)setProperRotation:(BOOL)rotation;
-(void)setProperRotation;
-(void)showSpinner;
-(void)setSubMessage:(id)message;
-(void)setCenterMessage:(id)message;
-(void)displayCompleted:(id)completed;
-(void)displayActivity:(id)activity;
-(void)hidden;
-(void)persist;
-(void)hide;
-(void)hideAfterDelay;
-(void)show;
-(void)dealloc;
@end

