/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKOAuthSharer.h"


__attribute__((visibility("hidden")))
@interface SHKDelicious : SHKOAuthSharer {
}
+(BOOL)canShareURL;
+(id)sharerTitle;
-(void)sendTicket:(id)ticket didFailWithError:(id)error;
-(void)sendTicket:(id)ticket didFinishWithData:(id)data;
-(BOOL)send;
-(id)shareFormFieldsForType:(int)type;
-(BOOL)handleResponse:(id)response;
-(void)tokenAccessModifyRequest:(id)request;
-(void)tokenRequestModifyRequest:(id)request;
-(id)init;
@end

