/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, UITextField, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SHKFormController : XXUnknownSuperclass <UITextFieldDelegate> {
@private
	id delegate;
	SEL validateSelector;
	SEL saveSelector;
	NSMutableArray* sections;
	NSMutableDictionary* values;
	float labelWidth;
	UITextField* activeField;
	BOOL autoSelect;
}
@property(assign) BOOL autoSelect;
@property(retain, nonatomic) UITextField* activeField;
@property(assign) float labelWidth;
@property(retain) NSMutableDictionary* values;
@property(retain) NSMutableArray* sections;
@property(assign) SEL saveSelector;
@property(assign) SEL validateSelector;
@property(retain) id delegate;
-(id)formValuesForSection:(int)section;
-(id)formValues;
-(void)saveForm;
-(void)validateForm;
-(void)cancel;
-(void)close;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(id)rowSettingsForIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)viewDidLoad;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)addSection:(id)section header:(id)header footer:(id)footer;
-(id)initWithStyle:(int)style title:(id)title rightButtonTitle:(id)title3;
-(void)dealloc;
@end

