/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SHKFormFieldSettings : XXUnknownSuperclass {
@private
	NSString* label;
	NSString* key;
	int type;
	NSString* start;
}
@property(retain, nonatomic) NSString* start;
@property(assign) int type;
@property(retain, nonatomic) NSString* key;
@property(retain, nonatomic) NSString* label;
+(id)label:(id)label key:(id)key type:(int)type start:(id)start;
-(void)dealloc;
@end

