/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UISwitch, SHKFormController, UITextField, SHKFormFieldSettings, NSString;

__attribute__((visibility("hidden")))
@interface SHKFormFieldCell : XXUnknownSuperclass {
@private
	SHKFormFieldSettings* settings;
	float labelWidth;
	UITextField* textField;
	UISwitch* toggle;
	NSString* tmpValue;
	SHKFormController* form;
}
@property(assign, nonatomic) SHKFormController* form;
@property(retain, nonatomic) NSString* tmpValue;
@property(retain, nonatomic) UISwitch* toggle;
@property(retain, nonatomic, getter=getTextField) UITextField* textField;
@property(assign, nonatomic) float labelWidth;
@property(retain) SHKFormFieldSettings* settings;
-(id)getValue;
-(void)setValue:(id)value;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)layoutSubviews;
-(void)dealloc;
@end

