/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKSharer.h"


__attribute__((visibility("hidden")))
@interface SHKInstapaper : SHKSharer {
}
+(id)authorizationFormCaption;
+(BOOL)canShare;
+(BOOL)canShareURL;
+(id)sharerTitle;
-(void)sendFinished:(id)finished;
-(BOOL)send;
-(id)shareFormFieldsForType:(int)type;
-(void)authFinished:(id)finished;
-(void)authorizationFormValidate:(id)validate;
@end

