/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSURL, NSData, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface SHKItem : XXUnknownSuperclass {
@private
	int shareType;
	NSURL* URL;
	UIImage* image;
	NSString* title;
	NSString* text;
	NSString* tags;
	NSData* data;
	NSString* mimeType;
	NSString* filename;
	NSMutableDictionary* custom;
}
@property(retain, nonatomic) NSMutableDictionary* custom;
@property(retain, nonatomic) NSString* filename;
@property(retain, nonatomic) NSString* mimeType;
@property(retain, nonatomic) NSData* data;
@property(retain, nonatomic) NSString* tags;
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) NSURL* URL;
@property(assign, nonatomic) int shareType;
+(id)itemFromDictionary:(id)dictionary;
+(id)file:(id)file filename:(id)filename mimeType:(id)type title:(id)title;
+(id)text:(id)text;
+(id)image:(id)image title:(id)title;
+(id)image:(id)image;
+(id)URL:(id)url title:(id)title;
+(id)URL:(id)url;
-(id)dictionaryRepresentation;
-(BOOL)customBoolForSwitchKey:(id)switchKey;
-(id)customValueForKey:(id)key;
-(void)setCustomValue:(id)value forKey:(id)key;
-(void)dealloc;
@end

