/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKSharer.h"
#import "MFMailComposeViewControllerDelegate.h"


__attribute__((visibility("hidden")))
@interface SHKMail : SHKSharer <MFMailComposeViewControllerDelegate> {
}
+(BOOL)canShare;
+(BOOL)requiresAuthentication;
+(BOOL)shareRequiresInternetConnection;
+(BOOL)canShareFile;
+(BOOL)canShareImage;
+(BOOL)canShareURL;
+(BOOL)canShareText;
+(id)sharerTitle;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(BOOL)sendMail;
-(BOOL)send;
-(BOOL)shouldAutoShare;
@end

