/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKSharer.h"

@class OAConsumer, NSURL, NSString, NSDictionary, OAToken;
@protocol OASignatureProviding;

__attribute__((visibility("hidden")))
@interface SHKOAuthSharer : SHKSharer {
@private
	NSString* consumerKey;
	NSString* secretKey;
	NSURL* authorizeCallbackURL;
	NSURL* authorizeURL;
	NSURL* accessURL;
	NSURL* requestURL;
	OAConsumer* consumer;
	OAToken* requestToken;
	OAToken* accessToken;
	id<OASignatureProviding> signatureProvider;
	NSDictionary* authorizeResponseQueryVars;
}
@property(retain, nonatomic) NSDictionary* authorizeResponseQueryVars;
@property(retain) id<OASignatureProviding> signatureProvider;
@property(retain) OAToken* accessToken;
@property(retain) OAToken* requestToken;
@property(retain) OAConsumer* consumer;
@property(retain, nonatomic) NSURL* requestURL;
@property(retain, nonatomic) NSURL* accessURL;
@property(retain, nonatomic) NSURL* authorizeURL;
@property(retain, nonatomic) NSURL* authorizeCallbackURL;
@property(retain, nonatomic) NSString* secretKey;
@property(retain, nonatomic) NSString* consumerKey;
+(void)logout;
+(void)deleteStoredAccessToken;
-(void)tryPendingAction;
-(void)refreshToken;
-(BOOL)restoreAccessToken;
-(void)storeAccessToken;
-(void)tokenAccessTicket:(id)ticket didFailWithError:(id)error;
-(void)tokenAccessTicket:(id)ticket didFinishWithData:(id)data;
-(void)tokenAccessModifyRequest:(id)request;
-(void)tokenAccess:(BOOL)access;
-(void)tokenAccess;
-(void)tokenAuthorizeCancelledView:(id)view;
-(void)tokenAuthorizeView:(id)view didFinishWithSuccess:(BOOL)success queryParams:(id)params error:(id)error;
-(void)tokenAuthorize;
-(void)tokenRequestTicket:(id)ticket didFailWithError:(id)error;
-(void)tokenRequestTicket:(id)ticket didFinishWithData:(id)data;
-(void)tokenRequestModifyRequest:(id)request;
-(void)tokenRequest;
-(void)promptAuthorization;
-(BOOL)isAuthorized;
-(void)dealloc;
@end

