/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKSharerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSThread, NSString, SHKItem, SHKSharer;

__attribute__((visibility("hidden")))
@interface SHKOfflineSharer : XXUnknownSuperclass <SHKSharerDelegate> {
@private
	SHKItem* item;
	NSString* sharerId;
	NSString* uid;
	BOOL readyToFinish;
	NSThread* runLoopThread;
	SHKSharer* sharer;
}
@property(retain, nonatomic) SHKSharer* sharer;
@property(retain, nonatomic) NSThread* runLoopThread;
@property(assign) BOOL readyToFinish;
@property(retain, nonatomic) NSString* uid;
@property(retain, nonatomic) NSString* sharerId;
@property(retain, nonatomic) SHKItem* item;
-(void)sharerCancelledSending:(id)sending;
-(void)sharer:(id)sharer failedWithError:(id)error shouldRelogin:(BOOL)relogin;
-(void)sharerFinishedSending:(id)sending;
-(void)sharerStartedSending:(id)sending;
-(void)lastSpin;
-(void)finish;
-(BOOL)shouldRun;
-(void)share;
-(void)main;
-(id)initWithItem:(id)item forSharer:(id)sharer uid:(id)uid;
-(void)dealloc;
@end

