/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIActivityIndicatorView, UIWebView;
@protocol SHKOAuthViewDelegate;

__attribute__((visibility("hidden")))
@interface SHKOAuthView : XXUnknownSuperclass <UIWebViewDelegate> {
@private
	UIWebView* webView;
	id delegate;
	UIActivityIndicatorView* spinner;
}
@property(retain, nonatomic) UIActivityIndicatorView* spinner;
@property(retain) id<SHKOAuthViewDelegate> delegate;
@property(retain, nonatomic) UIWebView* webView;
-(void)cancel;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)stopSpinner;
-(void)startSpinner;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)webViewDidFinishLoad:(id)webView;
-(void)webViewDidStartLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)viewDidDisappear:(BOOL)view;
-(void)loadView;
-(id)initWithURL:(id)url delegate:(id)delegate;
-(void)dealloc;
@end

