/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKSharer.h"


__attribute__((visibility("hidden")))
@interface SHKPinboard : SHKSharer {
}
+(id)authorizationFormCaption;
+(BOOL)canShareURL;
+(id)sharerTitle;
-(void)sendFinished:(id)finished;
-(BOOL)send;
-(id)shareFormFieldsForType:(int)type;
-(void)authFinished:(id)finished;
-(BOOL)handleResponse:(id)response;
-(void)authorizationFormValidate:(id)validate;
@end

