/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSString, NSDictionary, NSMutableData, NSHTTPURLResponse, NSURLConnection;

__attribute__((visibility("hidden")))
@interface SHKRequest : XXUnknownSuperclass {
@private
	NSURL* url;
	NSString* params;
	NSString* method;
	NSDictionary* headerFields;
	id delegate;
	SEL isFinishedSelector;
	NSURLConnection* connection;
	NSHTTPURLResponse* response;
	NSDictionary* headers;
	NSMutableData* data;
	NSString* result;
	BOOL success;
}
@property(assign, nonatomic) BOOL success;
@property(retain, getter=getResult) NSString* result;
@property(retain) NSMutableData* data;
@property(retain) NSDictionary* headers;
@property(retain) NSHTTPURLResponse* response;
@property(retain) NSURLConnection* connection;
@property(assign) SEL isFinishedSelector;
@property(assign) id delegate;
@property(retain) NSDictionary* headerFields;
@property(retain) NSString* method;
@property(retain) NSString* params;
@property(retain) NSURL* url;
-(void)finish;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)start;
-(id)initWithURL:(id)url params:(id)params delegate:(id)delegate isFinishedSelector:(SEL)selector method:(id)method autostart:(BOOL)autostart;
-(void)dealloc;
@end

