/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKSharer.h"


__attribute__((visibility("hidden")))
@interface SHKSafari : SHKSharer {
}
+(BOOL)requiresAuthentication;
+(BOOL)shareRequiresInternetConnection;
+(BOOL)canShareURL;
+(id)sharerTitle;
-(BOOL)send;
-(BOOL)shouldAutoShare;
@end

