/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SHKSharerDelegate
-(void)sharerCancelledSending:(id)sending;
-(void)sharer:(id)sharer failedWithError:(id)error shouldRelogin:(BOOL)relogin;
-(void)sharerFinishedSending:(id)sending;
-(void)sharerStartedSending:(id)sending;
@end

