/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, SHKItem, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SHKShareMenu : XXUnknownSuperclass {
@private
	SHKItem* item;
	NSMutableArray* tableData;
	NSMutableDictionary* exclusions;
}
@property(retain) NSMutableDictionary* exclusions;
@property(retain) NSMutableArray* tableData;
@property(retain) SHKItem* item;
-(void)save;
-(void)edit;
-(void)cancel;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(id)rowDataAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)section:(id)section;
-(void)rebuildTableDataAnimated:(BOOL)animated;
-(void)viewDidDisappear:(BOOL)view;
-(id)initWithStyle:(int)style;
-(void)dealloc;
@end

