/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "UITextViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UITextView;

__attribute__((visibility("hidden")))
@interface SHKTwitterForm : XXUnknownSuperclass <UITextViewDelegate> {
@private
	id delegate;
	UITextView* textView;
	UILabel* counter;
	BOOL hasAttachment;
}
@property(assign) BOOL hasAttachment;
@property(retain, nonatomic) UILabel* counter;
@property(retain, nonatomic) UITextView* textView;
@property(retain, nonatomic) id delegate;
-(void)save;
-(void)cancel;
-(void)textViewDidEndEditing:(id)textView;
-(void)textViewDidChange:(id)textView;
-(void)textViewDidBeginEditing:(id)textView;
-(void)layoutCounter;
-(void)updateCounter;
-(void)keyboardWillShow:(id)keyboard;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)loadView;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(void)dealloc;
@end

