/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SHKOAuthSharer.h"


__attribute__((visibility("hidden")))
@interface SHKTwitter : SHKOAuthSharer {
@private
	BOOL xAuth;
}
@property(assign) BOOL xAuth;
+(id)authorizationFormFields;
+(id)authorizationFormCaption;
+(BOOL)canShareImage;
+(BOOL)canShareText;
+(BOOL)canShareURL;
+(id)sharerTitle;
-(void)followMe;
-(void)sendImageTicket:(id)ticket didFailWithError:(id)error;
-(void)sendImageTicket:(id)ticket didFinishWithData:(id)data;
-(void)sendImage;
-(void)sendStatusTicket:(id)ticket didFailWithError:(id)error;
-(void)sendStatusTicket:(id)ticket didFinishWithData:(id)data;
-(void)sendStatus;
-(BOOL)send;
-(BOOL)validate;
-(void)shortenURLFinished:(id)finished;
-(void)shortenURL;
-(void)sendForm:(id)form;
-(void)showTwitterForm;
-(void)show;
-(void)tokenAccessTicket:(id)ticket didFinishWithData:(id)data;
-(void)tokenAccessModifyRequest:(id)request;
-(void)authorizationFormValidate:(id)validate;
-(void)promptAuthorization;
-(BOOL)isAuthorized;
-(BOOL)shouldAutoShare;
-(id)init;
@end

