/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"


__attribute__((visibility("hidden")))
@interface ShotsData : XXUnknownSuperclass {
@private
	BOOL isHit;
	float delay;
	BOOL isGrenadeLauncher;
	CGPoint position;
	float scale;
	int index;
	int weapon;
	int unitId;
	float damage;
	BOOL renderShotImpact;
	BOOL explosionFromGround;
	BOOL isStraightHit;
	BOOL alive;
}
@end

