/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SoundTiming : XXUnknownSuperclass {
@private
	NSString* soundName;
	float timeToPlay;
	BOOL play;
}
-(BOOL)play;
-(id)soundName;
-(void)update:(float)update;
-(id)initSoundTimingWithName:(id)name timeToPlay:(float)play;
-(void)dealloc;
@end

