/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"

@class Image;

__attribute__((visibility("hidden")))
@interface SpriteSheet : XXUnknownSuperclass {
@private
	Image* image;
	unsigned spriteWidth;
	unsigned spriteHeight;
	unsigned spacing;
	int horizontal;
	int vertical;
	Quad2* vertices;
	Quad2* texCoords;
}
@property(readonly, assign, nonatomic) Quad2* vertices;
@property(readonly, assign, nonatomic) Quad2* texCoords;
@property(readonly, assign, nonatomic) int vertical;
@property(readonly, assign, nonatomic) int horizontal;
@property(readonly, assign, nonatomic) unsigned spacing;
@property(readonly, assign, nonatomic) unsigned spriteHeight;
@property(readonly, assign, nonatomic) unsigned spriteWidth;
@property(readonly, assign, nonatomic) Image* image;
-(void)dealloc;
-(CGPoint)getOffsetForSpriteAtX:(int)x y:(int)y;
-(Quad2*)getVerticesForSpriteAtX:(unsigned)x y:(unsigned)y point:(CGPoint)point centerOfImage:(BOOL)image;
-(Quad2*)getTextureCoordsForSpriteAtX:(unsigned)x y:(unsigned)y;
-(void)renderSpriteAtX:(unsigned)x y:(unsigned)y point:(CGPoint)point centerOfImage:(BOOL)image;
-(id)getSpriteAtX:(unsigned)x y:(unsigned)y;
-(void)initImpl:(unsigned)impl spriteHeight:(unsigned)height spacing:(unsigned)spacing imageScale:(float)scale;
-(id)initWithImageNamed:(id)imageNamed spriteWidth:(unsigned)width spriteHeight:(unsigned)height spacing:(unsigned)spacing imageScale:(float)scale;
-(id)initWithImage:(id)image spriteWidth:(unsigned)width spriteHeight:(unsigned)height spacing:(unsigned)spacing;
@end

