/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */


@class Texture2D;

__attribute__((visibility("hidden")))
@interface Supply : NSObject {
@private
	float alpha;
	float scale;
	CGPoint position;
	float ratio;
	float health;
	int ammo;
	Texture2D* texture;
	int place;
	int layer;
	BOOL destroyed;
	BOOL effectEnded;
	BOOL infoTextEffectEnded;
	int type;
	float showTime;
	BOOL collected;
	BOOL collectedByServer;
	BOOL _iPod4WithScale;
	int weaponIndex;
	int value;
}
-(void)setSupplyValue:(int)value;
-(int)getValue;
-(int)weaponIndex;
-(void)setWeaponIndex:(int)index;
-(void)setUsingIPod4WithScale:(BOOL)scale;
-(BOOL)isCollected;
-(void)setCollected:(BOOL)collected;
-(float)showTime;
-(void)setShowTime:(float)time;
-(int)supplyType;
-(BOOL)isInfoTextEffectEnded;
-(void)setInfoTextEffectEnded:(BOOL)ended;
-(BOOL)isEffectEnded;
-(void)setEffectEnded:(BOOL)ended;
-(BOOL)isRewardForYou;
-(BOOL)isCollectedByServer;
-(void)setCollectedByServer:(BOOL)server;
-(BOOL)isDestroyed;
-(void)setDestroyed:(BOOL)destroyed;
-(int)getLayer;
-(int)place;
-(void)setPlace:(int)place;
-(void)setAmmo:(int)ammo;
-(int)ammo;
-(void)setHealth:(float)health;
-(float)health;
-(void)setRatio:(float)ratio;
-(float)getScale;
-(float)scale;
-(void)setScale:(float)scale;
-(CGPoint)position;
-(void)setPosition:(CGPoint)position;
-(float)alpha;
-(void)setAlpha:(float)alpha;
-(id)texture;
-(void)setTexture:(id)texture;
-(BOOL)touchToSupply:(CGPoint)supply;
-(void)drawSupply:(CGPoint)supply;
-(void)updateSupply:(float)supply;
-(id)initWithValue:(int)value supplyType:(int)type place:(int)place layer:(int)layer position:(CGPoint)position scale:(float)scale showTime:(float)time;
-(id)initWithAmmo:(int)ammo place:(int)place layer:(int)layer position:(CGPoint)position scale:(float)scale showTime:(float)time;
-(id)initWithHealth:(float)health place:(int)place layer:(int)layer position:(CGPoint)position scale:(float)scale showTime:(float)time;
-(id)initSupplyTemplate:(int)aTemplate layer:(int)layer position:(CGPoint)position scale:(float)scale;
-(void)dealloc;
@end

