/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SupportItems : XXUnknownSuperclass {
@private
	int multiplayer_flashGrenade;
	int multiplayer_stunGrenade;
	int multiplayer_airstrike;
	int flashGrenade;
	int airstrike;
	BOOL multiplayer_flashGrenade_isEquipped;
	BOOL multiplayer_stunGrenade_isEquipped;
	BOOL multiplayer_airstrike_isEquipped;
	BOOL flashGrenade_isEquipped;
	BOOL airstrike_isEquipped;
	BOOL multiplayer_flashGrenade_used;
	BOOL multiplayer_stunGrenade_used;
	BOOL multiplayer_airstrike_used;
	BOOL flashGrenade_used;
	BOOL airstrike_used;
	BOOL multiplayer_flashGrenade_canUseInGame;
	BOOL multiplayer_stunGrenade_canUseInGame;
	BOOL multiplayer_airstrike_canUseInGame;
	BOOL flashGrenade_canUseInGame;
	BOOL airstrike_canUseInGame;
}
+(id)sharedSupportItems;
-(BOOL)buy:(int)buy;
-(BOOL)spend:(int)spend;
-(BOOL)add:(int)add;
-(int)getPrice:(int)price;
-(int)getValue:(int)value;
-(void)setEquipOrUnequip:(int)unequip;
-(BOOL)canUseInGame:(int)game;
-(BOOL)isEquipped:(int)equipped;
-(void)setUsed:(BOOL)used item:(int)item;
-(BOOL)isUsed:(int)used;
-(void)singleplayer_restartItems;
-(void)multiplayer_restartItems;
-(void)load;
-(void)save;
-(id)init;
@end

