/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Foundation.h"

@class NSMutableDictionary, WeaponsCampView, NSMutableArray, Particle, SingletonSoundManager, NSString;

@class ScoreEffect;
typedef struct PlaceForScoreEffect {
	CGPoint position;
	BOOL free;
	ScoreEffect* scoreEffect;
} PlaceForScoreEffect;

@interface Target : Foundation {
@private
	WeaponsCampView* weapv;
	int unitType;
	NSString* effectKey;
	NSString* destroyEffectKey;
	NSMutableDictionary* effectsDictionary;
	NSMutableDictionary* dTargetZones;
	NSMutableDictionary* dTargetTexNames;
	NSMutableArray* _particle_blood;
	NSMutableArray* textureFeatures;
	BOOL isDestroyAnimationEnded;
	BOOL escaped;
	BOOL destroyed;
	int scoreForShot;
	PlaceForScoreEffect placeForScoreEffect[6];
	NSMutableArray* _effectArray;
	NSMutableArray* _secondEffectArray;
	NSMutableArray* _destroyEffectArray;
	int type;
	int difficulty;
	int place;
	Particle* _particle;
	Particle* _muzzleParicle;
	BOOL isTemplate;
	float showAtTime;
	float pauseBetweenShoots;
	float timeToShot;
	float duration_preparingTimeToShot;
	float time_startPreparingToShot;
	int shotCount;
	int shotCounter;
	int animatedShotCount;
	int animatedShotCounter;
	float time_firstStartShooting;
	NSMutableArray* _shotTimingArray;
	BOOL invertScale;
	int red;
	int green;
	int blue;
	BOOL enabledType1;
	BOOL enabledType2;
	BOOL enabledType3;
	int circle_red;
	int circle_green;
	int circle_blue;
	BOOL circle_segment[6];
	BOOL showCircle;
	int circle_timeToShot;
	int hitCounter;
	SingletonSoundManager* sharedSoundManager;
	int enableInvertScale;
	NSMutableArray* time_startShootingArray;
	int shootingArrayIndex;
	CGPoint gamutOffset;
	BOOL playingSound;
	BOOL sound_death;
	BOOL deathCounted;
	BOOL inBuilding;
	BOOL isHeadShot;
	float lastDamage;
	int team;
	BOOL showTeamSign;
	int unitId;
}
//-(id).cxx_construct;
-(BOOL)showTeamSign;
-(BOOL)isAlive;
-(int)getTeam;
-(void)setTeam:(int)team;
-(int)getUnitId;
-(BOOL)isHeadShot;
-(BOOL)isInBuilding;
-(void)setInBuilding:(BOOL)building;
-(BOOL)isDeathCounted;
-(void)setDeathCounted:(BOOL)counted;
-(void)setSoundPlayed_death:(BOOL)death;
-(BOOL)isSoundPlayed_death;
-(BOOL)isPlayingSound;
-(void)setPlayingSound:(BOOL)sound;
-(CGPoint)gamutOffset;
-(void)setGamutOffset:(CGPoint)offset;
-(id)starShootingArray;
-(int)difficulty;
-(int)unitType;
-(BOOL)showCircle;
-(BOOL)circle_segment:(int)segment;
-(int)circle_blue;
-(int)circle_green;
-(int)circle_red;
-(int)type;
-(BOOL)enabledType3;
-(BOOL)enabledType2;
-(BOOL)enabledType1;
-(int)blue;
-(int)green;
-(int)red;
-(BOOL)invertScale;
-(id)shotTimingArray;
-(float)getScale;
-(void)setScale:(float)scale;
-(id)particle_blood;
-(id)muzzleParticle;
-(id)particle;
-(float)showAtTime;
-(int)getLayer;
-(int)place;
-(int)scoreForShot;
-(BOOL)destroyed;
-(void)setDestroyed:(BOOL)destroyed;
-(BOOL)escaped;
-(void)setEscaped:(BOOL)escaped;
-(int)animatedShotCount;
-(int)shotCount;
-(float)pauseBetweenShoots;
-(void)setDestroyAnimationEnded:(BOOL)ended;
-(BOOL)isDestroyAnimationEnded;
-(id)textureFeatures;
-(id)destroyEffectKey;
-(void)setDestroyEffectKey:(id)key;
-(id)effectKey;
-(void)setEffectKey:(id)key;
-(int)enableInvertScale;
-(int)score_explosion;
-(float)distanceOfExplosion:(CGPoint)explosion;
-(BOOL)pointWithinEllipse:(CGPoint)ellipse radiantsA:(float)a radiantsB:(float)b location:(CGPoint)location;
-(BOOL)isTargetInExplosiveArea:(CGPoint)explosiveArea bombard:(BOOL)bombard;
-(CGPoint)shellPoint;
-(void)doDamage:(float)damage;
-(BOOL)touchToTargetZone:(CGPoint)targetZone targetAbsPosition:(CGPoint)position damage:(float)damage;
-(BOOL)touchToTargetZone:(CGPoint)targetZone targetAbsPosition:(CGPoint)position;
-(id)arrayOfRects_textureParts;
-(id)arrayOfRects_targetZone;
-(BOOL)touchToTarget:(CGPoint)target damage:(float)damage;
-(BOOL)touchToTarget:(CGPoint)target;
-(CGPoint)absoluteTargetPosition;
-(float)distanceBetweenTwoPoints:(CGPoint)points toPoint:(CGPoint)point;
-(void)updateCircleGamut:(float)gamut;
-(void)updateParticleOfShot:(float)shot;
-(float)getLastDamage;
-(void)getHit;
-(id)destroyEffectArray;
-(id)secondEffectArray;
-(id)effectArray;
-(void)resetTarget;
-(void)setNextShotWithFirstShot:(BOOL)firstShot;
-(id)scoreEffectsWithIndex:(int)index;
-(void)updateAllScoreEffects;
-(void)createScoreEffectsWithScore:(int)score headShot:(BOOL)shot color:(Color)color;
-(void)dealloc;
-(id)initWithPosition:(CGPoint)position unitId:(int)anId team:(int)team place:(int)place showAtTime:(float)time layer:(int)layer alpha:(float)alpha scale:(float)scale invertScale:(BOOL)scale9 unitType:(int)type difficulty:(int)difficulty type:(int)type12 pauseBetweenShoots:(float)shoots shotCount:(int)count animatedShotCount:(int)count15 duration_preparingTimeToShot:(float)shot damage:(float)damage r:(int)r g:(int)g b:(int)b enabledType1:(BOOL)a1 enabledType2:(BOOL)a2 enabledType3:(BOOL)a3 circle_red:(int)red circle_green:(int)green circle_blue:(int)blue particle:(id)particle muzzleParticle:(id)particle28 health:(float)health effectArray:(id)array secondEffectArray:(id)array31 destroyEffectArray:(id)array32 textureDictionary:(id)dictionary textureNamesDictionaty:(id)dictionaty targetZoneDictionary:(id)dictionary35 ParentClass:(id)aClass;
-(id)initTargetTemplateWithPosition:(CGPoint)position place:(int)place layer:(int)layer alpha:(float)alpha scale:(float)scale health:(float)health damage:(float)damage inBuilding:(BOOL)building r:(int)r g:(int)g b:(int)b enabledType1:(BOOL)a1 enabledType2:(BOOL)a2 enabledType3:(BOOL)a3 enableInvertScale:(int)scale15 unitType:(int)type effectArray:(id)array secondEffectArray:(id)array18 destroyEffectKey:(id)key ParentClass:(id)aClass;
-(CGRect)getArea;
-(float)highestVuln;
-(BOOL)behindObstacle:(NSMutableArray*)_container;
@end

