/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "TBXML.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface TBXML : XXUnknownSuperclass {
@private
	TBXMLElement* rootXMLElement;
	TBXMLElementBuffer* currentElementBuffer;
	TBXMLAttributeBuffer* currentAttributeBuffer;
	long currentElement;
	long currentAttribute;
	char* bytes;
	long bytesLength;
}
@property(readonly, assign, nonatomic) TBXMLElement* rootXMLElement;
+(id)tbxmlWithXMLData:(id)xmldata;
+(id)tbxmlWithXMLString:(id)xmlstring;
+(id)tbxmlWithURL:(id)url;
-(id)initWithXMLData:(id)xmldata;
-(id)initWithXMLString:(id)xmlstring;
-(id)initWithURL:(id)url;
-(id)init;
@end

@interface TBXML (StaticFunctions)
+(TBXMLElement*)nextSiblingNamed:(id)named searchFromElement:(TBXMLElement*)element;
+(TBXMLElement*)childElementNamed:(id)named parentElement:(TBXMLElement*)element;
+(id)valueOfAttributeNamed:(id)attributeNamed forElement:(TBXMLElement*)element;
+(int)negativeNumberForUnknownElement:(TBXMLElement*)unknownElement;
+(BOOL)boolForElement:(TBXMLElement*)element;
+(int)numberForElement:(TBXMLElement*)element;
+(id)textForElement:(TBXMLElement*)element;
+(id)attributeValue:(TBXMLAttribute*)value;
+(id)attributeName:(TBXMLAttribute*)name;
+(id)elementName:(TBXMLElement*)name;
@end

@interface TBXML (Private)
-(TBXMLAttribute*)nextAvailableAttribute;
-(TBXMLElement*)nextAvailableElement;
-(void)dealloc;
-(void)decodeBytes;
-(void)decodeData:(id)data;
@end

