/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */
 // Unknown library

@class NSString, SingletonTextureManager;

@interface Texture2D : NSObject {
@private
	SingletonTextureManager* sharedTextureManager;
	NSString* textureName;
	unsigned _name;
	CGSize _size;
	unsigned _width;
	unsigned _height;
	int _format;
	int memoryUsage;
	float _maxS;
	float _maxT;
}
@property(readonly, assign) float maxT;
@property(readonly, assign) float maxS;
@property(readonly, assign, nonatomic) CGSize contentSize;
@property(readonly, assign) unsigned name;
@property(readonly, assign) unsigned pixelsHigh;
@property(readonly, assign) unsigned pixelsWide;
@property(readonly, assign) int pixelFormat;
-(id)description;
-(void)getAllMemory;
-(void)dealloc;
-(float)getMemory;
-(id)initWithData:(const void*)data pixelFormat:(int)format pixelsWide:(unsigned)wide pixelsHigh:(unsigned)high contentSize:(CGSize)size;
@end

@interface Texture2D (Image)
-(id)initWithImage:(id)image name:(id)name;
-(id)initWithImage:(id)image;
@end

@interface Texture2D (Text)
-(id)initWithString:(id)string dimensions:(CGSize)dimensions alignment:(int)alignment fontName:(id)name fontSize:(float)size fontBold:(BOOL)bold;
@end

@interface Texture2D (Drawing)
-(void)drawParu:(CGPoint)paru currentFrame:(int)frame width:(int)width height:(int)height texWidth:(int)width5 texHight:(int)hight;
-(void)drawClient:(CGPoint)client currentFrame:(int)frame;
-(void)drawAtPoint:(CGPoint)point currentFrame:(int)frame width:(int)width height:(int)height texWidth:(int)width5 texHight:(int)hight type:(int)type;
-(void)drawAtPoint:(CGPoint)point crop:(CGPoint)crop fromCorner:(int)corner;
-(void)drawInRect:(CGRect)rect;
-(void)drawAtMiddle:(CGPoint)middle;
-(void)drawEdge:(CGPoint)edge;
-(void)drawAtPoint:(CGPoint)point withAlignment:(int)alignment;
-(void)drawAtPoint:(CGPoint)point;
-(CGSize)getSize;
@end

