/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "TJCCallsWrapper.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface TJCCallsWrapper : XXUnknownSuperclass {
@private
	int currentInterfaceOrientation;
}
@property(assign) int currentInterfaceOrientation;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedTJCCallsWrapper;
-(void)dealloc;
-(void)moveViewToFront;
-(void)updateViewsWithOrientation:(int)orientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)showBoxCloseNotification:(id)notification;
-(void)viewDidLoad;
-(id)init;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

@interface TJCCallsWrapper (TJCFeaturedAppViewHandler)
-(void)showFeaturedAppFullScreenAd:(id)ad withViewController:(id)viewController;
-(id)showFeaturedAppFullScreenAd:(id)ad withFrame:(CGRect)frame;
-(id)showFeaturedAppFullScreenAdWithURL:(id)url;
@end

@interface TJCCallsWrapper (TJCOffersViewHandler)
-(void)showOffersWithCurrencyID:(id)currencyID withViewController:(id)viewController withInternalNavBar:(BOOL)internalNavBar withCurrencySelector:(BOOL)currencySelector;
-(void)showOffersWithCurrencyID:(id)currencyID withViewController:(id)viewController withCurrencySelector:(BOOL)currencySelector;
-(id)showOffersWithCurrencyID:(id)currencyID withCurrencySelector:(BOOL)currencySelector;
-(id)showOffersWithCurrencyID:(id)currencyID withFrame:(CGRect)frame withCurrencySelector:(BOOL)currencySelector;
-(void)showOffersWithViewController:(id)viewController withInternalNavBar:(BOOL)internalNavBar;
-(void)showOffersWithViewController:(id)viewController;
-(id)showOffers;
-(id)showOffersWithFrame:(CGRect)frame;
@end

@interface TJCCallsWrapper (TJCVideoViewHandler)
-(void)showVideoAdWithViewController:(id)viewController offerID:(id)anId;
-(void)showVideoAdWithOfferID:(id)offerID;
-(id)showVideoAdWithFrame:(CGRect)frame offerID:(id)anId;
@end

