/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class TJCCoreFetcher;
@protocol TJCFetchResponseDelegate;

__attribute__((visibility("hidden")))
@interface TJCCoreFetcherHandler : XXUnknownSuperclass {
@private
	id<TJCFetchResponseDelegate> deleg_;
	int requestTag_;
	TJCCoreFetcher* myFetcher_;
}
-(void)dealloc;
-(void)makeRequestWithURL:(id)url withInvoker:(id)invoker;
-(TBXMLElement*)validateResponseReturnedObject:(id)object;
-(TBXMLElement*)parseReturnObjectAsTBXMLElement:(id)element;
-(void)makeGenericPOSTRequestWithURL:(id)url alternateURL:(id)url2 data:(id)data params:(id)params selector:(SEL)selector;
-(void)makeGenericRequestWithURL:(id)url alternateURL:(id)url2 params:(id)params selector:(SEL)selector;
-(id)initRequestWithDelegate:(id)delegate andRequestTag:(int)tag;
@end

