/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TJCCoreFetcherHandler.h"
#import "TJCWebFetcherDelegate.h"


__attribute__((visibility("hidden")))
@interface TJCFeaturedAppRequestHandler : TJCCoreFetcherHandler <TJCWebFetcherDelegate> {
}
-(void)dealloc;
-(void)featuredAppDataReceived:(id)received;
-(void)requestFeaturedAppWithCurrencyID:(id)currencyID;
-(void)requestFeaturedApp;
-(id)initRequestWithDelegate:(id)delegate andRequestTag:(int)tag;
@end

