/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface TJCFeaturedAppViewHandler : XXUnknownSuperclass {
}
+(void)showFullScreenAdWithURL:(id)url withViewController:(id)viewController;
+(id)showFullScreenAdWithURL:(id)url withFrame:(CGRect)frame;
+(id)showFullScreenAdWithURL:(id)url;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedTJCFeaturedAppViewHandler;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

