/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TJCFetchResponseDelegate.h"
#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class TJCFeaturedAppModel, TJCFeaturedAppRequestHandler;

__attribute__((visibility("hidden")))
@interface TJCFeaturedAppManager : XXUnknownSuperclass <TJCFetchResponseDelegate> {
@private
	TJCFeaturedAppRequestHandler* featuredAppHandlerObj_;
	TJCFeaturedAppModel* featuredAppModelObj_;
	int featuredAppDisplayCount_;
}
@property(assign, nonatomic) int featuredAppDisplayCount;
@property(retain, nonatomic) TJCFeaturedAppModel* featuredAppModelObj;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedTJCFeaturedAppManager;
-(void)dealloc;
-(void)releaseFeaturedAppHandler;
-(void)fetchResponseError:(int)error errorDescription:(id)description requestTag:(int)tag;
-(void)fetchResponseSuccessWithData:(void*)data withRequestTag:(int)requestTag;
-(void)getFeaturedAppWithCurrencyID:(id)currencyID;
-(void)getFeaturedApp;
-(id)init;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

