/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TJCUIWebPageView.h"
#import "Overkill-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TJCFeaturedAppView : TJCUIWebPageView {
@private
	NSString* currencyID_;
	NSString* publisherUserID_;
}
@property(copy) NSString* publisherUserID_;
@property(copy) NSString* currencyID_;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedTJCFeaturedAppView;
-(void)dealloc;
-(void)initializeWebViewUI;
-(void)handleWebViewUI;
-(void)updateViewWithOrientation:(int)orientation;
-(void)giveBackNotification;
-(void)backtoGameAction:(id)action;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
-(void)webViewDidFinishLoad:(id)webView;
-(void)webViewDidStartLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)loadViewWithURL:(id)url;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(id)setUpFeaturedAdURLWithServiceURL:(id)serviceURL;
-(void)refreshWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

