/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIActivityIndicatorView, UIView, UILabel;

__attribute__((visibility("hidden")))
@interface TJCLoadingView : XXUnknownSuperclass {
@private
	UIView* loadingBG;
	UIActivityIndicatorView* activityIndicator;
	UILabel* loadingLabel;
	UIView* containerView;
	UIView* mainView;
}
@property(retain, nonatomic) UIView* mainView;
-(void)dealloc;
-(void)fadeOut;
-(void)fadeIn;
-(void)enable;
-(void)disable;
-(id)initWithFrame:(CGRect)frame;
@end

