/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"


__attribute__((visibility("hidden")))
@interface TJCOffersViewHandler : XXUnknownSuperclass {
}
+(void)showOffersWithCurrencyID:(id)currencyID withViewController:(id)viewController withInternalNavBar:(BOOL)internalNavBar withCurrencySelector:(BOOL)currencySelector;
+(void)showOffersWithCurrencyID:(id)currencyID withViewController:(id)viewController withCurrencySelector:(BOOL)currencySelector;
+(id)showOffersWithCurrencyID:(id)currencyID withCurrencySelector:(BOOL)currencySelector;
+(id)showOffersWithCurrencyID:(id)currencyID withFrame:(CGRect)frame withCurrencySelector:(BOOL)currencySelector;
+(void)showOffersWithViewController:(id)viewController withInternalNavBar:(BOOL)internalNavBar;
+(void)showOffersWithViewController:(id)viewController;
+(id)showOffers;
+(id)showOffersWithFrame:(CGRect)frame;
@end

