/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface TJCUserAccountModel : XXUnknownSuperclass {
@private
	int tapPoints_;
	NSString* pointsID_;
	NSString* currencyName_;
}
@property(retain, nonatomic) NSString* currencyName;
@property(retain, nonatomic) NSString* pointsID;
@property(assign, nonatomic) int tapPoints;
-(void)dealloc;
-(void)updateWithTBXML:(TBXMLElement*)tbxml shouldCheckEarnedPoints:(BOOL)points;
-(id)initWithTBXML:(TBXMLElement*)tbxml;
-(id)init;
@end

