/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "TJCFetchResponseDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class TJCUserAccountModel, TJCUserAccountRequestHandler;

__attribute__((visibility("hidden")))
@interface TJCUserAccountManager : XXUnknownSuperclass <TJCFetchResponseDelegate> {
@private
	TJCUserAccountModel* userAccountModelObj_;
	TJCUserAccountRequestHandler* userAccountGetTapPointsObj_;
	TJCUserAccountRequestHandler* userAccountSpendTapPointsObj_;
	BOOL waitingForResponse_;
}
@property(readonly, assign, nonatomic) TJCUserAccountModel* userAccountModelObj;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedTJCUserAccountManager;
-(void)dealloc;
-(void)releaseUserAccount;
-(void)fetchResponseError:(int)error errorDescription:(id)description requestTag:(int)tag;
-(void)fetchResponseSuccessWithData:(void*)data withRequestTag:(int)requestTag;
-(void)awardTapPoints:(int)points;
-(void)spendTapPoints:(int)points;
-(void)getTapPoints;
-(void)updateUserAccountObjWithTBXMLElement:(TBXMLElement*)tbxmlelement;
-(id)init;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

