/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UINavigationItem, UIBarButtonItem, UIImage, UINavigationBar, UILabel;

__attribute__((visibility("hidden")))
@interface TJCUINavigationBarView : XXUnknownSuperclass {
@private
	UINavigationBar* navBar;
	UINavigationItem* navBarTitle;
	UIBarButtonItem* navBarLeftBtn;
	UIBarButtonItem* navBarRightBtn;
	UIImage* bgImage;
	UILabel* titleLabel;
}
@property(readonly, assign, nonatomic) UILabel* titleLabel;
@property(readonly, assign, nonatomic) UIBarButtonItem* navBarRightBtn;
@property(readonly, assign, nonatomic) UIBarButtonItem* navBarLeftBtn;
@property(readonly, assign, nonatomic) UINavigationItem* navBarTitle;
@property(readonly, assign, nonatomic) UINavigationBar* navBar;
-(void)dealloc;
-(void)addRightButtonTarget:(id)target action:(SEL)action forControlEvents:(unsigned)controlEvents;
-(void)addLeftButtonTarget:(id)target action:(SEL)action forControlEvents:(unsigned)controlEvents;
-(void)setNavBarRightBtnWithTitle:(id)title;
-(void)setNavBarLeftBtnWithTitle:(id)title;
-(void)setNavBarRightBtn:(id)btn;
-(void)setNavBarLeftBtn:(id)btn;
-(void)updateRightNavBarBtnWithTitle:(id)title;
-(void)updateLeftNavBarBtnWithTitle:(id)title;
-(void)setCustomBackgroundImage:(id)image;
-(id)initWithTitle:(id)title withFrame:(CGRect)frame AtY:(int)y;
-(id)initWithFrame:(CGRect)frame;
@end

