/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "UIWebViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class TJCLoadingView, NSURLRequest, NSString, UIWebView;

__attribute__((visibility("hidden")))
@interface TJCUIWebPageView : XXUnknownSuperclass <UIWebViewDelegate> {
@private
	UIWebView* cWebView_;
	NSURLRequest* lastClickedURL_;
	id delegate_;
	BOOL webPageRendered_;
	NSString* lastURL_;
	TJCLoadingView* loadingView_;
	BOOL isViewVisible_;
}
@property(assign, nonatomic) BOOL isViewVisible;
@property(retain, nonatomic) NSString* lastURL;
-(void)dealloc;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)webViewDidFinishLoad:(id)webView;
-(void)webViewDidStartLoad:(id)webView;
-(void)setDelegate:(id)delegate;
-(void)loadURLRequest:(id)request withTimeOutInterval:(int)timeOutInterval;
-(void)loadURLRequest:(id)request;
-(void)loadWebRequest:(id)request;
-(id)initWithFrame:(CGRect)frame WithRequestURL:(id)requestURL;
-(id)appendGenericParamsWithURL:(id)url;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(id)initWithFrame:(CGRect)frame;
@end

