/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"


__attribute__((visibility("hidden")))
@interface TJCVideoViewHandler : XXUnknownSuperclass {
}
+(void)showVideoAdWithViewController:(id)viewController offerID:(id)anId;
+(id)showVideoAdWithOfferID:(id)offerID;
+(id)showVideoAdWithFrame:(CGRect)frame offerID:(id)anId;
@end

