/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Overkill-Structs.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface TJCViewCommons : XXUnknownSuperclass {
@private
	int currentTransitionEffect_;
	int reverseTransitionEffect_;
	int viewsIntegrationType_;
	int primaryColorCode_;
	UIColor* userDefinedColor_;
	float transitionDelay_;
}
+(void)animateTJCView:(id)view withTJCTransition:(int)tjctransition withDelay:(float)delay;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedTJCViewCommons;
-(void)dealloc;
-(void)setUserDefinedColorWithRed:(int)red WithGreen:(int)green WithBlue:(int)blue;
-(void)setUserdefinedColorWithIntValue:(int)intValue;
-(id)getUserDefinedColor;
-(int)getUserDefinedColorCode;
-(int)getReverseTransitionEffect;
-(int)getCurrentTransitionEffect;
-(void)setTransitionEffect:(int)effect;
-(float)getTransitionDelay;
-(void)removeTempView:(id)view;
-(void)runExpandTransition:(id)transition;
-(id)init;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

