/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TJCCoreFetcherHandler.h"
#import "TJCWebFetcherDelegate.h"


__attribute__((visibility("hidden")))
@interface TJCVideoRequestHandler : TJCCoreFetcherHandler <TJCWebFetcherDelegate> {
@private
	BOOL clickSuccessful_;
}
@property(assign) BOOL clickSuccessful;
-(void)videoCompleteReceived:(id)received;
-(void)videoClickReceived:(id)received;
-(void)videoDataReceived:(id)received;
-(void)requestVideoCompleteWithOfferID:(id)offerID;
-(void)recordVideoClickWithURL:(id)url;
-(void)requestVideoData;
-(id)initRequestWithDelegate:(id)delegate andRequestTag:(int)tag;
@end

