/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Foundation.h"
#import "Overkill-Structs.h"


__attribute__((visibility("hidden")))
@interface Upgrade : Foundation {
@private
	int medals;
	int numberOfWinsToUnlock;
}
-(int)numberOfWinsToUnlock;
-(void)dealloc;
-(int)medals;
-(void)setMedals:(int)medals;
-(id)initWithAccuracy:(float)accuracy damage:(float)damage fireRate:(float)rate cadence:(int)cadence reloadSpeed:(float)speed ammoQuantity:(int)quantity price:(int)price isBought:(BOOL)bought markPosition:(CGPoint)position upgradeMenu_position:(CGPoint)position10 upgradeMenu_scale:(float)scale name:(id)name allFeatures:(float)features isGrenadeLauncher:(BOOL)launcher numberOfWinsToUnlock:(int)unlock medals:(int)medals;
-(id)initWithAccuracy:(float)accuracy damage:(float)damage fireRate:(float)rate cadence:(int)cadence reloadSpeed:(float)speed ammoQuantity:(int)quantity price:(int)price isBought:(BOOL)bought markPosition:(CGPoint)position upgradeMenu_position:(CGPoint)position10 upgradeMenu_scale:(float)scale name:(id)name allFeatures:(float)features isGrenadeLauncher:(BOOL)launcher;
@end

