/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Overkill-Structs.h"
#import "Foundation.h"

@class NSMutableDictionary, NSArray, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface Weapon : Foundation {
@private
	CGPoint stockPosition;
	CGPoint cartPosition;
	CGPoint scopePosition;
	CGPoint barellPosition;
	CGPoint mouthPosition;
	CGPoint mStockPosition;
	CGPoint mCartPosition;
	CGPoint mScopePosition;
	CGPoint mBarellPosition;
	CGPoint mMouthPosition;
	int _equipedUpgrades[5];
	int _equipedUpgrades_forGame[5];
	NSMutableArray* _upgStock;
	NSMutableArray* _upgCart;
	NSMutableArray* _upgScope;
	NSMutableArray* _upgBarell;
	NSMutableArray* _upgMouth;
	NSArray* _upgrades;
	int weaponType;
	float zoomMin;
	float zoomMax;
	float zoomForGunShop;
	CGPoint centerOfZoom;
	CGPoint transForGunShop;
	NSMutableArray* tWeapon;
	NSString* weaponName;
	int ammo1_price;
	int ammo2_price;
	int ammo1_buyQuantity;
	int ammo2_buyQuantity;
	int ammo1_boughtQuantity;
	int ammo2_boughtQuantity;
	BOOL locked;
	int medals;
	BOOL loadedAllTextures;
	CGPoint weaponPosition;
	float screenShift;
	CGPoint ratio;
	id weaponShop;
	NSMutableDictionary* dShopDictionary;
}
-(id).cxx_construct;
-(void)setLoadedAllTextures:(BOOL)textures;
-(BOOL)isLoadedAllTextures;
-(int)medals;
-(BOOL)isLocked;
-(CGPoint)transForGunShop;
-(float)zoomForGunShop;
-(CGPoint)centerOfZoom;
-(float)zoomMin;
-(float)zoomMax;
-(CGPoint)MouthPosition;
-(CGPoint)BarellPosition;
-(CGPoint)ScopePosition;
-(CGPoint)CartPosition;
-(CGPoint)StockPosition;
-(id)tWeapon;
-(int*)equipedUpgrades_forGame;
-(int*)equipedUpgrades;
-(id)upgMouth;
-(id)upgBarell;
-(id)upgScope;
-(id)upgCart;
-(id)upgStock;
-(id)upgrades;
-(int)ammo2_boughtQuantity;
-(int)ammo1_boughtQuantity;
-(int)ammo2_buyQuantity;
-(int)ammo1_buyQuantity;
-(int)ammo2_price;
-(int)ammo1_price;
-(CGRect)getSizeAndPositionMark:(int)mark;
-(CGRect)getSizeAndPositionPart:(int)part;
-(int)upgradeCountWithPart:(int)part;
-(CGPoint)weaponPosition;
-(void)setMedals:(int)medals;
-(void)setLock:(BOOL)lock;
-(void)setTransForGunShop:(CGPoint)gunShop;
-(void)setZoomForGunShop:(float)gunShop;
-(void)setCenterOfZoom:(CGPoint)zoom;
-(void)setZoomMax:(float)max;
-(void)setZoomMin:(float)min;
-(void)setMarksPositionOnParts;
-(void)setMouthPosition:(CGPoint)position;
-(void)setBarellPosition:(CGPoint)position;
-(void)setScopePosition:(CGPoint)position;
-(void)setCartPosition:(CGPoint)position;
-(void)setStockPosition:(CGPoint)position;
-(void)setMMouthPosition:(CGPoint)position;
-(void)setMBarellPosition:(CGPoint)position;
-(void)setMScopePosition:(CGPoint)position;
-(void)setMCartPosition:(CGPoint)position;
-(void)setMStockPosition:(CGPoint)position;
-(void)setAmmo2_boughtQuantity:(int)quantity;
-(void)setAmmo1_boughtQuantity:(int)quantity;
-(void)setAmmo2_buyQuantity:(int)quantity;
-(void)setAmmo1_buyQuantity:(int)quantity;
-(void)setAmmo2_price:(int)price;
-(void)setAmmo1_price:(int)price;
-(void)setWeaponPosition:(CGPoint)position;
-(void)setUpgradeWithPart:(int)part upgrade:(int)upgrade;
-(void)setUpgradesWithStock:(int)stock upgrCart:(int)cart upgrScope:(int)scope upgrBarell:(int)barell upgrMouth:(int)mouth;
-(void)setPartPosition:(CGPoint)position Part:(int)part;
-(void)setActualUpgrade;
-(id)weaponName;
-(void)setWeaponName:(id)name;
-(BOOL)canBuyUpgrade:(int)upgrade;
-(int)sellAmmo;
-(void)sellWeapon;
-(int)upgradeCount;
-(int)buyedUpgradeCount;
-(int)sellPrice;
-(void)drawMarksWithAlpha:(float)alpha scale:(float)scale selectedMark:(int)mark;
-(void)drawParts:(int)parts weapon:(int)weapon;
-(void)dealloc;
-(id)initWithType:(int)type weaponName:(id)name accuracy:(float)accuracy damage:(float)damage fireRate:(float)rate cadence:(int)cadence reloadSpeed:(float)speed price:(int)price isBought:(BOOL)bought weaponTextureArray:(id)array ratio:(CGPoint)ratio screenShift:(float)shift dShopTextures:(id)textures ParentClass:(id)aClass;
@end

